Netlist(Freeze)
Netlist(Clear)
Netlist(Add,unnamed_net36,LED61-1)
Netlist(Add,unnamed_net36,LED62-1)
Netlist(Add,unnamed_net35,LED59-1)
Netlist(Add,unnamed_net35,LED60-1)
Netlist(Add,unnamed_net34,LED57-1)
Netlist(Add,unnamed_net34,LED58-1)
Netlist(Add,unnamed_net33,LED55-1)
Netlist(Add,unnamed_net33,LED56-1)
Netlist(Add,unnamed_net32,LED53-1)
Netlist(Add,unnamed_net32,LED54-1)
Netlist(Add,unnamed_net31,LED51-1)
Netlist(Add,unnamed_net31,LED52-1)
Netlist(Add,unnamed_net30,LED49-1)
Netlist(Add,unnamed_net30,LED50-1)
Netlist(Add,unnamed_net29,LED47-1)
Netlist(Add,unnamed_net29,LED48-1)
Netlist(Add,unnamed_net28,LED45-1)
Netlist(Add,unnamed_net28,LED46-1)
Netlist(Add,unnamed_net27,LED43-1)
Netlist(Add,unnamed_net27,LED44-1)
Netlist(Add,unnamed_net26,LED41-1)
Netlist(Add,unnamed_net26,LED42-1)
Netlist(Add,unnamed_net25,LED39-1)
Netlist(Add,unnamed_net25,LED40-1)
Netlist(Add,unnamed_net24,LED25-1)
Netlist(Add,unnamed_net24,LED26-1)
Netlist(Add,unnamed_net23,LED23-1)
Netlist(Add,unnamed_net23,LED24-1)
Netlist(Add,unnamed_net22,LED21-1)
Netlist(Add,unnamed_net22,LED22-1)
Netlist(Add,unnamed_net21,LED19-1)
Netlist(Add,unnamed_net21,LED20-1)
Netlist(Add,unnamed_net20,LED17-1)
Netlist(Add,unnamed_net20,LED18-1)
Netlist(Add,unnamed_net19,LED15-1)
Netlist(Add,unnamed_net19,LED16-1)
Netlist(Add,unnamed_net18,LED37-1)
Netlist(Add,unnamed_net18,LED38-1)
Netlist(Add,unnamed_net17,LED35-1)
Netlist(Add,unnamed_net17,LED36-1)
Netlist(Add,unnamed_net16,LED33-1)
Netlist(Add,unnamed_net16,LED34-1)
Netlist(Add,unnamed_net15,LED31-1)
Netlist(Add,unnamed_net15,LED32-1)
Netlist(Add,unnamed_net14,LED29-1)
Netlist(Add,unnamed_net14,LED30-1)
Netlist(Add,unnamed_net13,LED27-1)
Netlist(Add,unnamed_net13,LED28-1)
Netlist(Add,unnamed_net12,LED85-1)
Netlist(Add,unnamed_net12,LED86-1)
Netlist(Add,unnamed_net11,LED83-1)
Netlist(Add,unnamed_net11,LED84-1)
Netlist(Add,unnamed_net10,LED81-1)
Netlist(Add,unnamed_net10,LED82-1)
Netlist(Add,unnamed_net9,LED79-1)
Netlist(Add,unnamed_net9,LED80-1)
Netlist(Add,unnamed_net8,LED77-1)
Netlist(Add,unnamed_net8,LED78-1)
Netlist(Add,unnamed_net7,LED75-1)
Netlist(Add,unnamed_net7,LED76-1)
Netlist(Add,unnamed_net6,LED73-1)
Netlist(Add,unnamed_net6,LED74-1)
Netlist(Add,unnamed_net5,LED71-1)
Netlist(Add,unnamed_net5,LED72-1)
Netlist(Add,unnamed_net4,LED69-1)
Netlist(Add,unnamed_net4,LED70-1)
Netlist(Add,unnamed_net3,LED67-1)
Netlist(Add,unnamed_net3,LED68-1)
Netlist(Add,unnamed_net2,LED65-1)
Netlist(Add,unnamed_net2,LED66-1)
Netlist(Add,unnamed_net1,LED63-1)
Netlist(Add,unnamed_net1,LED64-1)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"LED61","T1.75_LED.fp","unknown")
ElementSetAttr("LED61","device","LED")
ElementSetAttr("LED61","manufacturer","unknown")
ElementSetAttr("LED61","manufacturer_part_number","unknown")
ElementSetAttr("LED61","vendor","unknown")
ElementSetAttr("LED61","vendor_part_number","unknown")
ChangePinName("LED61", 2, "K")
ChangePinName("LED61", 1, "A")
ElementList(Need,"LED59","T1.75_LED.fp","unknown")
ElementSetAttr("LED59","device","LED")
ElementSetAttr("LED59","manufacturer","unknown")
ElementSetAttr("LED59","manufacturer_part_number","unknown")
ElementSetAttr("LED59","vendor","unknown")
ElementSetAttr("LED59","vendor_part_number","unknown")
ChangePinName("LED59", 2, "K")
ChangePinName("LED59", 1, "A")
ElementList(Need,"LED57","T1.75_LED.fp","unknown")
ElementSetAttr("LED57","device","LED")
ElementSetAttr("LED57","manufacturer","unknown")
ElementSetAttr("LED57","manufacturer_part_number","unknown")
ElementSetAttr("LED57","vendor","unknown")
ElementSetAttr("LED57","vendor_part_number","unknown")
ChangePinName("LED57", 2, "K")
ChangePinName("LED57", 1, "A")
ElementList(Need,"LED55","T1.75_LED.fp","unknown")
ElementSetAttr("LED55","device","LED")
ElementSetAttr("LED55","manufacturer","unknown")
ElementSetAttr("LED55","manufacturer_part_number","unknown")
ElementSetAttr("LED55","vendor","unknown")
ElementSetAttr("LED55","vendor_part_number","unknown")
ChangePinName("LED55", 2, "K")
ChangePinName("LED55", 1, "A")
ElementList(Need,"LED53","T1.75_LED.fp","unknown")
ElementSetAttr("LED53","device","LED")
ElementSetAttr("LED53","manufacturer","unknown")
ElementSetAttr("LED53","manufacturer_part_number","unknown")
ElementSetAttr("LED53","vendor","unknown")
ElementSetAttr("LED53","vendor_part_number","unknown")
ChangePinName("LED53", 2, "K")
ChangePinName("LED53", 1, "A")
ElementList(Need,"LED51","T1.75_LED.fp","unknown")
ElementSetAttr("LED51","device","LED")
ElementSetAttr("LED51","manufacturer","unknown")
ElementSetAttr("LED51","manufacturer_part_number","unknown")
ElementSetAttr("LED51","vendor","unknown")
ElementSetAttr("LED51","vendor_part_number","unknown")
ChangePinName("LED51", 2, "K")
ChangePinName("LED51", 1, "A")
ElementList(Need,"LED62","T1.75_LED.fp","unknown")
ElementSetAttr("LED62","device","LED")
ElementSetAttr("LED62","manufacturer","unknown")
ElementSetAttr("LED62","manufacturer_part_number","unknown")
ElementSetAttr("LED62","vendor","unknown")
ElementSetAttr("LED62","vendor_part_number","unknown")
ChangePinName("LED62", 2, "K")
ChangePinName("LED62", 1, "A")
ElementList(Need,"LED60","T1.75_LED.fp","unknown")
ElementSetAttr("LED60","device","LED")
ElementSetAttr("LED60","manufacturer","unknown")
ElementSetAttr("LED60","manufacturer_part_number","unknown")
ElementSetAttr("LED60","vendor","unknown")
ElementSetAttr("LED60","vendor_part_number","unknown")
ChangePinName("LED60", 2, "K")
ChangePinName("LED60", 1, "A")
ElementList(Need,"LED58","T1.75_LED.fp","unknown")
ElementSetAttr("LED58","device","LED")
ElementSetAttr("LED58","manufacturer","unknown")
ElementSetAttr("LED58","manufacturer_part_number","unknown")
ElementSetAttr("LED58","vendor","unknown")
ElementSetAttr("LED58","vendor_part_number","unknown")
ChangePinName("LED58", 2, "K")
ChangePinName("LED58", 1, "A")
ElementList(Need,"LED56","T1.75_LED.fp","unknown")
ElementSetAttr("LED56","device","LED")
ElementSetAttr("LED56","manufacturer","unknown")
ElementSetAttr("LED56","manufacturer_part_number","unknown")
ElementSetAttr("LED56","vendor","unknown")
ElementSetAttr("LED56","vendor_part_number","unknown")
ChangePinName("LED56", 2, "K")
ChangePinName("LED56", 1, "A")
ElementList(Need,"LED54","T1.75_LED.fp","unknown")
ElementSetAttr("LED54","device","LED")
ElementSetAttr("LED54","manufacturer","unknown")
ElementSetAttr("LED54","manufacturer_part_number","unknown")
ElementSetAttr("LED54","vendor","unknown")
ElementSetAttr("LED54","vendor_part_number","unknown")
ChangePinName("LED54", 2, "K")
ChangePinName("LED54", 1, "A")
ElementList(Need,"LED52","T1.75_LED.fp","unknown")
ElementSetAttr("LED52","device","LED")
ElementSetAttr("LED52","manufacturer","unknown")
ElementSetAttr("LED52","manufacturer_part_number","unknown")
ElementSetAttr("LED52","vendor","unknown")
ElementSetAttr("LED52","vendor_part_number","unknown")
ChangePinName("LED52", 2, "K")
ChangePinName("LED52", 1, "A")
ElementList(Need,"LED49","T1.75_LED.fp","unknown")
ElementSetAttr("LED49","device","LED")
ElementSetAttr("LED49","manufacturer","unknown")
ElementSetAttr("LED49","manufacturer_part_number","unknown")
ElementSetAttr("LED49","vendor","unknown")
ElementSetAttr("LED49","vendor_part_number","unknown")
ChangePinName("LED49", 2, "K")
ChangePinName("LED49", 1, "A")
ElementList(Need,"LED47","T1.75_LED.fp","unknown")
ElementSetAttr("LED47","device","LED")
ElementSetAttr("LED47","manufacturer","unknown")
ElementSetAttr("LED47","manufacturer_part_number","unknown")
ElementSetAttr("LED47","vendor","unknown")
ElementSetAttr("LED47","vendor_part_number","unknown")
ChangePinName("LED47", 2, "K")
ChangePinName("LED47", 1, "A")
ElementList(Need,"LED45","T1.75_LED.fp","unknown")
ElementSetAttr("LED45","device","LED")
ElementSetAttr("LED45","manufacturer","unknown")
ElementSetAttr("LED45","manufacturer_part_number","unknown")
ElementSetAttr("LED45","vendor","unknown")
ElementSetAttr("LED45","vendor_part_number","unknown")
ChangePinName("LED45", 2, "K")
ChangePinName("LED45", 1, "A")
ElementList(Need,"LED43","T1.75_LED.fp","unknown")
ElementSetAttr("LED43","device","LED")
ElementSetAttr("LED43","manufacturer","unknown")
ElementSetAttr("LED43","manufacturer_part_number","unknown")
ElementSetAttr("LED43","vendor","unknown")
ElementSetAttr("LED43","vendor_part_number","unknown")
ChangePinName("LED43", 2, "K")
ChangePinName("LED43", 1, "A")
ElementList(Need,"LED41","T1.75_LED.fp","unknown")
ElementSetAttr("LED41","device","LED")
ElementSetAttr("LED41","manufacturer","unknown")
ElementSetAttr("LED41","manufacturer_part_number","unknown")
ElementSetAttr("LED41","vendor","unknown")
ElementSetAttr("LED41","vendor_part_number","unknown")
ChangePinName("LED41", 2, "K")
ChangePinName("LED41", 1, "A")
ElementList(Need,"LED39","T1.75_LED.fp","unknown")
ElementSetAttr("LED39","device","LED")
ElementSetAttr("LED39","manufacturer","unknown")
ElementSetAttr("LED39","manufacturer_part_number","unknown")
ElementSetAttr("LED39","vendor","unknown")
ElementSetAttr("LED39","vendor_part_number","unknown")
ChangePinName("LED39", 2, "K")
ChangePinName("LED39", 1, "A")
ElementList(Need,"LED50","T1.75_LED.fp","unknown")
ElementSetAttr("LED50","device","LED")
ElementSetAttr("LED50","manufacturer","unknown")
ElementSetAttr("LED50","manufacturer_part_number","unknown")
ElementSetAttr("LED50","vendor","unknown")
ElementSetAttr("LED50","vendor_part_number","unknown")
ChangePinName("LED50", 2, "K")
ChangePinName("LED50", 1, "A")
ElementList(Need,"LED48","T1.75_LED.fp","unknown")
ElementSetAttr("LED48","device","LED")
ElementSetAttr("LED48","manufacturer","unknown")
ElementSetAttr("LED48","manufacturer_part_number","unknown")
ElementSetAttr("LED48","vendor","unknown")
ElementSetAttr("LED48","vendor_part_number","unknown")
ChangePinName("LED48", 2, "K")
ChangePinName("LED48", 1, "A")
ElementList(Need,"LED46","T1.75_LED.fp","unknown")
ElementSetAttr("LED46","device","LED")
ElementSetAttr("LED46","manufacturer","unknown")
ElementSetAttr("LED46","manufacturer_part_number","unknown")
ElementSetAttr("LED46","vendor","unknown")
ElementSetAttr("LED46","vendor_part_number","unknown")
ChangePinName("LED46", 2, "K")
ChangePinName("LED46", 1, "A")
ElementList(Need,"LED44","T1.75_LED.fp","unknown")
ElementSetAttr("LED44","device","LED")
ElementSetAttr("LED44","manufacturer","unknown")
ElementSetAttr("LED44","manufacturer_part_number","unknown")
ElementSetAttr("LED44","vendor","unknown")
ElementSetAttr("LED44","vendor_part_number","unknown")
ChangePinName("LED44", 2, "K")
ChangePinName("LED44", 1, "A")
ElementList(Need,"LED42","T1.75_LED.fp","unknown")
ElementSetAttr("LED42","device","LED")
ElementSetAttr("LED42","manufacturer","unknown")
ElementSetAttr("LED42","manufacturer_part_number","unknown")
ElementSetAttr("LED42","vendor","unknown")
ElementSetAttr("LED42","vendor_part_number","unknown")
ChangePinName("LED42", 2, "K")
ChangePinName("LED42", 1, "A")
ElementList(Need,"LED40","T1.75_LED.fp","unknown")
ElementSetAttr("LED40","device","LED")
ElementSetAttr("LED40","manufacturer","unknown")
ElementSetAttr("LED40","manufacturer_part_number","unknown")
ElementSetAttr("LED40","vendor","unknown")
ElementSetAttr("LED40","vendor_part_number","unknown")
ChangePinName("LED40", 2, "K")
ChangePinName("LED40", 1, "A")
ElementList(Need,"LED25","T1.75_LED.fp","unknown")
ElementSetAttr("LED25","device","LED")
ElementSetAttr("LED25","manufacturer","unknown")
ElementSetAttr("LED25","manufacturer_part_number","unknown")
ElementSetAttr("LED25","vendor","unknown")
ElementSetAttr("LED25","vendor_part_number","unknown")
ChangePinName("LED25", 2, "K")
ChangePinName("LED25", 1, "A")
ElementList(Need,"LED23","T1.75_LED.fp","unknown")
ElementSetAttr("LED23","device","LED")
ElementSetAttr("LED23","manufacturer","unknown")
ElementSetAttr("LED23","manufacturer_part_number","unknown")
ElementSetAttr("LED23","vendor","unknown")
ElementSetAttr("LED23","vendor_part_number","unknown")
ChangePinName("LED23", 2, "K")
ChangePinName("LED23", 1, "A")
ElementList(Need,"LED21","T1.75_LED.fp","unknown")
ElementSetAttr("LED21","device","LED")
ElementSetAttr("LED21","manufacturer","unknown")
ElementSetAttr("LED21","manufacturer_part_number","unknown")
ElementSetAttr("LED21","vendor","unknown")
ElementSetAttr("LED21","vendor_part_number","unknown")
ChangePinName("LED21", 2, "K")
ChangePinName("LED21", 1, "A")
ElementList(Need,"LED19","T1.75_LED.fp","unknown")
ElementSetAttr("LED19","device","LED")
ElementSetAttr("LED19","manufacturer","unknown")
ElementSetAttr("LED19","manufacturer_part_number","unknown")
ElementSetAttr("LED19","vendor","unknown")
ElementSetAttr("LED19","vendor_part_number","unknown")
ChangePinName("LED19", 2, "K")
ChangePinName("LED19", 1, "A")
ElementList(Need,"LED17","T1.75_LED.fp","unknown")
ElementSetAttr("LED17","device","LED")
ElementSetAttr("LED17","manufacturer","unknown")
ElementSetAttr("LED17","manufacturer_part_number","unknown")
ElementSetAttr("LED17","vendor","unknown")
ElementSetAttr("LED17","vendor_part_number","unknown")
ChangePinName("LED17", 2, "K")
ChangePinName("LED17", 1, "A")
ElementList(Need,"LED15","T1.75_LED.fp","unknown")
ElementSetAttr("LED15","device","LED")
ElementSetAttr("LED15","manufacturer","unknown")
ElementSetAttr("LED15","manufacturer_part_number","unknown")
ElementSetAttr("LED15","vendor","unknown")
ElementSetAttr("LED15","vendor_part_number","unknown")
ChangePinName("LED15", 2, "K")
ChangePinName("LED15", 1, "A")
ElementList(Need,"LED26","T1.75_LED.fp","unknown")
ElementSetAttr("LED26","device","LED")
ElementSetAttr("LED26","manufacturer","unknown")
ElementSetAttr("LED26","manufacturer_part_number","unknown")
ElementSetAttr("LED26","vendor","unknown")
ElementSetAttr("LED26","vendor_part_number","unknown")
ChangePinName("LED26", 2, "K")
ChangePinName("LED26", 1, "A")
ElementList(Need,"LED24","T1.75_LED.fp","unknown")
ElementSetAttr("LED24","device","LED")
ElementSetAttr("LED24","manufacturer","unknown")
ElementSetAttr("LED24","manufacturer_part_number","unknown")
ElementSetAttr("LED24","vendor","unknown")
ElementSetAttr("LED24","vendor_part_number","unknown")
ChangePinName("LED24", 2, "K")
ChangePinName("LED24", 1, "A")
ElementList(Need,"LED22","T1.75_LED.fp","unknown")
ElementSetAttr("LED22","device","LED")
ElementSetAttr("LED22","manufacturer","unknown")
ElementSetAttr("LED22","manufacturer_part_number","unknown")
ElementSetAttr("LED22","vendor","unknown")
ElementSetAttr("LED22","vendor_part_number","unknown")
ChangePinName("LED22", 2, "K")
ChangePinName("LED22", 1, "A")
ElementList(Need,"LED20","T1.75_LED.fp","unknown")
ElementSetAttr("LED20","device","LED")
ElementSetAttr("LED20","manufacturer","unknown")
ElementSetAttr("LED20","manufacturer_part_number","unknown")
ElementSetAttr("LED20","vendor","unknown")
ElementSetAttr("LED20","vendor_part_number","unknown")
ChangePinName("LED20", 2, "K")
ChangePinName("LED20", 1, "A")
ElementList(Need,"LED18","T1.75_LED.fp","unknown")
ElementSetAttr("LED18","device","LED")
ElementSetAttr("LED18","manufacturer","unknown")
ElementSetAttr("LED18","manufacturer_part_number","unknown")
ElementSetAttr("LED18","vendor","unknown")
ElementSetAttr("LED18","vendor_part_number","unknown")
ChangePinName("LED18", 2, "K")
ChangePinName("LED18", 1, "A")
ElementList(Need,"LED16","T1.75_LED.fp","unknown")
ElementSetAttr("LED16","device","LED")
ElementSetAttr("LED16","manufacturer","unknown")
ElementSetAttr("LED16","manufacturer_part_number","unknown")
ElementSetAttr("LED16","vendor","unknown")
ElementSetAttr("LED16","vendor_part_number","unknown")
ChangePinName("LED16", 2, "K")
ChangePinName("LED16", 1, "A")
ElementList(Need,"LED37","T1.75_LED.fp","unknown")
ElementSetAttr("LED37","device","LED")
ElementSetAttr("LED37","manufacturer","unknown")
ElementSetAttr("LED37","manufacturer_part_number","unknown")
ElementSetAttr("LED37","vendor","unknown")
ElementSetAttr("LED37","vendor_part_number","unknown")
ChangePinName("LED37", 2, "K")
ChangePinName("LED37", 1, "A")
ElementList(Need,"LED35","T1.75_LED.fp","unknown")
ElementSetAttr("LED35","device","LED")
ElementSetAttr("LED35","manufacturer","unknown")
ElementSetAttr("LED35","manufacturer_part_number","unknown")
ElementSetAttr("LED35","vendor","unknown")
ElementSetAttr("LED35","vendor_part_number","unknown")
ChangePinName("LED35", 2, "K")
ChangePinName("LED35", 1, "A")
ElementList(Need,"LED33","T1.75_LED.fp","unknown")
ElementSetAttr("LED33","device","LED")
ElementSetAttr("LED33","manufacturer","unknown")
ElementSetAttr("LED33","manufacturer_part_number","unknown")
ElementSetAttr("LED33","vendor","unknown")
ElementSetAttr("LED33","vendor_part_number","unknown")
ChangePinName("LED33", 2, "K")
ChangePinName("LED33", 1, "A")
ElementList(Need,"LED31","T1.75_LED.fp","unknown")
ElementSetAttr("LED31","device","LED")
ElementSetAttr("LED31","manufacturer","unknown")
ElementSetAttr("LED31","manufacturer_part_number","unknown")
ElementSetAttr("LED31","vendor","unknown")
ElementSetAttr("LED31","vendor_part_number","unknown")
ChangePinName("LED31", 2, "K")
ChangePinName("LED31", 1, "A")
ElementList(Need,"LED29","T1.75_LED.fp","unknown")
ElementSetAttr("LED29","device","LED")
ElementSetAttr("LED29","manufacturer","unknown")
ElementSetAttr("LED29","manufacturer_part_number","unknown")
ElementSetAttr("LED29","vendor","unknown")
ElementSetAttr("LED29","vendor_part_number","unknown")
ChangePinName("LED29", 2, "K")
ChangePinName("LED29", 1, "A")
ElementList(Need,"LED27","T1.75_LED.fp","unknown")
ElementSetAttr("LED27","device","LED")
ElementSetAttr("LED27","manufacturer","unknown")
ElementSetAttr("LED27","manufacturer_part_number","unknown")
ElementSetAttr("LED27","vendor","unknown")
ElementSetAttr("LED27","vendor_part_number","unknown")
ChangePinName("LED27", 2, "K")
ChangePinName("LED27", 1, "A")
ElementList(Need,"LED38","T1.75_LED.fp","unknown")
ElementSetAttr("LED38","device","LED")
ElementSetAttr("LED38","manufacturer","unknown")
ElementSetAttr("LED38","manufacturer_part_number","unknown")
ElementSetAttr("LED38","vendor","unknown")
ElementSetAttr("LED38","vendor_part_number","unknown")
ChangePinName("LED38", 2, "K")
ChangePinName("LED38", 1, "A")
ElementList(Need,"LED36","T1.75_LED.fp","unknown")
ElementSetAttr("LED36","device","LED")
ElementSetAttr("LED36","manufacturer","unknown")
ElementSetAttr("LED36","manufacturer_part_number","unknown")
ElementSetAttr("LED36","vendor","unknown")
ElementSetAttr("LED36","vendor_part_number","unknown")
ChangePinName("LED36", 2, "K")
ChangePinName("LED36", 1, "A")
ElementList(Need,"LED34","T1.75_LED.fp","unknown")
ElementSetAttr("LED34","device","LED")
ElementSetAttr("LED34","manufacturer","unknown")
ElementSetAttr("LED34","manufacturer_part_number","unknown")
ElementSetAttr("LED34","vendor","unknown")
ElementSetAttr("LED34","vendor_part_number","unknown")
ChangePinName("LED34", 2, "K")
ChangePinName("LED34", 1, "A")
ElementList(Need,"LED32","T1.75_LED.fp","unknown")
ElementSetAttr("LED32","device","LED")
ElementSetAttr("LED32","manufacturer","unknown")
ElementSetAttr("LED32","manufacturer_part_number","unknown")
ElementSetAttr("LED32","vendor","unknown")
ElementSetAttr("LED32","vendor_part_number","unknown")
ChangePinName("LED32", 2, "K")
ChangePinName("LED32", 1, "A")
ElementList(Need,"LED30","T1.75_LED.fp","unknown")
ElementSetAttr("LED30","device","LED")
ElementSetAttr("LED30","manufacturer","unknown")
ElementSetAttr("LED30","manufacturer_part_number","unknown")
ElementSetAttr("LED30","vendor","unknown")
ElementSetAttr("LED30","vendor_part_number","unknown")
ChangePinName("LED30", 2, "K")
ChangePinName("LED30", 1, "A")
ElementList(Need,"LED28","T1.75_LED.fp","unknown")
ElementSetAttr("LED28","device","LED")
ElementSetAttr("LED28","manufacturer","unknown")
ElementSetAttr("LED28","manufacturer_part_number","unknown")
ElementSetAttr("LED28","vendor","unknown")
ElementSetAttr("LED28","vendor_part_number","unknown")
ChangePinName("LED28", 2, "K")
ChangePinName("LED28", 1, "A")
ElementList(Need,"LED85","T1.75_LED.fp","unknown")
ElementSetAttr("LED85","device","LED")
ElementSetAttr("LED85","manufacturer","unknown")
ElementSetAttr("LED85","manufacturer_part_number","unknown")
ElementSetAttr("LED85","vendor","unknown")
ElementSetAttr("LED85","vendor_part_number","unknown")
ChangePinName("LED85", 2, "K")
ChangePinName("LED85", 1, "A")
ElementList(Need,"LED83","T1.75_LED.fp","unknown")
ElementSetAttr("LED83","device","LED")
ElementSetAttr("LED83","manufacturer","unknown")
ElementSetAttr("LED83","manufacturer_part_number","unknown")
ElementSetAttr("LED83","vendor","unknown")
ElementSetAttr("LED83","vendor_part_number","unknown")
ChangePinName("LED83", 2, "K")
ChangePinName("LED83", 1, "A")
ElementList(Need,"LED81","T1.75_LED.fp","unknown")
ElementSetAttr("LED81","device","LED")
ElementSetAttr("LED81","manufacturer","unknown")
ElementSetAttr("LED81","manufacturer_part_number","unknown")
ElementSetAttr("LED81","vendor","unknown")
ElementSetAttr("LED81","vendor_part_number","unknown")
ChangePinName("LED81", 2, "K")
ChangePinName("LED81", 1, "A")
ElementList(Need,"LED79","T1.75_LED.fp","unknown")
ElementSetAttr("LED79","device","LED")
ElementSetAttr("LED79","manufacturer","unknown")
ElementSetAttr("LED79","manufacturer_part_number","unknown")
ElementSetAttr("LED79","vendor","unknown")
ElementSetAttr("LED79","vendor_part_number","unknown")
ChangePinName("LED79", 2, "K")
ChangePinName("LED79", 1, "A")
ElementList(Need,"LED77","T1.75_LED.fp","unknown")
ElementSetAttr("LED77","device","LED")
ElementSetAttr("LED77","manufacturer","unknown")
ElementSetAttr("LED77","manufacturer_part_number","unknown")
ElementSetAttr("LED77","vendor","unknown")
ElementSetAttr("LED77","vendor_part_number","unknown")
ChangePinName("LED77", 2, "K")
ChangePinName("LED77", 1, "A")
ElementList(Need,"LED75","T1.75_LED.fp","unknown")
ElementSetAttr("LED75","device","LED")
ElementSetAttr("LED75","manufacturer","unknown")
ElementSetAttr("LED75","manufacturer_part_number","unknown")
ElementSetAttr("LED75","vendor","unknown")
ElementSetAttr("LED75","vendor_part_number","unknown")
ChangePinName("LED75", 2, "K")
ChangePinName("LED75", 1, "A")
ElementList(Need,"LED86","T1.75_LED.fp","unknown")
ElementSetAttr("LED86","device","LED")
ElementSetAttr("LED86","manufacturer","unknown")
ElementSetAttr("LED86","manufacturer_part_number","unknown")
ElementSetAttr("LED86","vendor","unknown")
ElementSetAttr("LED86","vendor_part_number","unknown")
ChangePinName("LED86", 2, "K")
ChangePinName("LED86", 1, "A")
ElementList(Need,"LED84","T1.75_LED.fp","unknown")
ElementSetAttr("LED84","device","LED")
ElementSetAttr("LED84","manufacturer","unknown")
ElementSetAttr("LED84","manufacturer_part_number","unknown")
ElementSetAttr("LED84","vendor","unknown")
ElementSetAttr("LED84","vendor_part_number","unknown")
ChangePinName("LED84", 2, "K")
ChangePinName("LED84", 1, "A")
ElementList(Need,"LED82","T1.75_LED.fp","unknown")
ElementSetAttr("LED82","device","LED")
ElementSetAttr("LED82","manufacturer","unknown")
ElementSetAttr("LED82","manufacturer_part_number","unknown")
ElementSetAttr("LED82","vendor","unknown")
ElementSetAttr("LED82","vendor_part_number","unknown")
ChangePinName("LED82", 2, "K")
ChangePinName("LED82", 1, "A")
ElementList(Need,"LED80","T1.75_LED.fp","unknown")
ElementSetAttr("LED80","device","LED")
ElementSetAttr("LED80","manufacturer","unknown")
ElementSetAttr("LED80","manufacturer_part_number","unknown")
ElementSetAttr("LED80","vendor","unknown")
ElementSetAttr("LED80","vendor_part_number","unknown")
ChangePinName("LED80", 2, "K")
ChangePinName("LED80", 1, "A")
ElementList(Need,"LED78","T1.75_LED.fp","unknown")
ElementSetAttr("LED78","device","LED")
ElementSetAttr("LED78","manufacturer","unknown")
ElementSetAttr("LED78","manufacturer_part_number","unknown")
ElementSetAttr("LED78","vendor","unknown")
ElementSetAttr("LED78","vendor_part_number","unknown")
ChangePinName("LED78", 2, "K")
ChangePinName("LED78", 1, "A")
ElementList(Need,"LED76","T1.75_LED.fp","unknown")
ElementSetAttr("LED76","device","LED")
ElementSetAttr("LED76","manufacturer","unknown")
ElementSetAttr("LED76","manufacturer_part_number","unknown")
ElementSetAttr("LED76","vendor","unknown")
ElementSetAttr("LED76","vendor_part_number","unknown")
ChangePinName("LED76", 2, "K")
ChangePinName("LED76", 1, "A")
ElementList(Need,"LED73","T1.75_LED.fp","unknown")
ElementSetAttr("LED73","device","LED")
ElementSetAttr("LED73","manufacturer","unknown")
ElementSetAttr("LED73","manufacturer_part_number","unknown")
ElementSetAttr("LED73","vendor","unknown")
ElementSetAttr("LED73","vendor_part_number","unknown")
ChangePinName("LED73", 2, "K")
ChangePinName("LED73", 1, "A")
ElementList(Need,"LED71","T1.75_LED.fp","unknown")
ElementSetAttr("LED71","device","LED")
ElementSetAttr("LED71","manufacturer","unknown")
ElementSetAttr("LED71","manufacturer_part_number","unknown")
ElementSetAttr("LED71","vendor","unknown")
ElementSetAttr("LED71","vendor_part_number","unknown")
ChangePinName("LED71", 2, "K")
ChangePinName("LED71", 1, "A")
ElementList(Need,"LED69","T1.75_LED.fp","unknown")
ElementSetAttr("LED69","device","LED")
ElementSetAttr("LED69","manufacturer","unknown")
ElementSetAttr("LED69","manufacturer_part_number","unknown")
ElementSetAttr("LED69","vendor","unknown")
ElementSetAttr("LED69","vendor_part_number","unknown")
ChangePinName("LED69", 2, "K")
ChangePinName("LED69", 1, "A")
ElementList(Need,"LED67","T1.75_LED.fp","unknown")
ElementSetAttr("LED67","device","LED")
ElementSetAttr("LED67","manufacturer","unknown")
ElementSetAttr("LED67","manufacturer_part_number","unknown")
ElementSetAttr("LED67","vendor","unknown")
ElementSetAttr("LED67","vendor_part_number","unknown")
ChangePinName("LED67", 2, "K")
ChangePinName("LED67", 1, "A")
ElementList(Need,"LED65","T1.75_LED.fp","unknown")
ElementSetAttr("LED65","device","LED")
ElementSetAttr("LED65","manufacturer","unknown")
ElementSetAttr("LED65","manufacturer_part_number","unknown")
ElementSetAttr("LED65","vendor","unknown")
ElementSetAttr("LED65","vendor_part_number","unknown")
ChangePinName("LED65", 2, "K")
ChangePinName("LED65", 1, "A")
ElementList(Need,"LED63","T1.75_LED.fp","unknown")
ElementSetAttr("LED63","device","LED")
ElementSetAttr("LED63","manufacturer","unknown")
ElementSetAttr("LED63","manufacturer_part_number","unknown")
ElementSetAttr("LED63","vendor","unknown")
ElementSetAttr("LED63","vendor_part_number","unknown")
ChangePinName("LED63", 2, "K")
ChangePinName("LED63", 1, "A")
ElementList(Need,"LED74","T1.75_LED.fp","unknown")
ElementSetAttr("LED74","device","LED")
ElementSetAttr("LED74","manufacturer","unknown")
ElementSetAttr("LED74","manufacturer_part_number","unknown")
ElementSetAttr("LED74","vendor","unknown")
ElementSetAttr("LED74","vendor_part_number","unknown")
ChangePinName("LED74", 2, "K")
ChangePinName("LED74", 1, "A")
ElementList(Need,"LED72","T1.75_LED.fp","unknown")
ElementSetAttr("LED72","device","LED")
ElementSetAttr("LED72","manufacturer","unknown")
ElementSetAttr("LED72","manufacturer_part_number","unknown")
ElementSetAttr("LED72","vendor","unknown")
ElementSetAttr("LED72","vendor_part_number","unknown")
ChangePinName("LED72", 2, "K")
ChangePinName("LED72", 1, "A")
ElementList(Need,"LED70","T1.75_LED.fp","unknown")
ElementSetAttr("LED70","device","LED")
ElementSetAttr("LED70","manufacturer","unknown")
ElementSetAttr("LED70","manufacturer_part_number","unknown")
ElementSetAttr("LED70","vendor","unknown")
ElementSetAttr("LED70","vendor_part_number","unknown")
ChangePinName("LED70", 2, "K")
ChangePinName("LED70", 1, "A")
ElementList(Need,"LED68","T1.75_LED.fp","unknown")
ElementSetAttr("LED68","device","LED")
ElementSetAttr("LED68","manufacturer","unknown")
ElementSetAttr("LED68","manufacturer_part_number","unknown")
ElementSetAttr("LED68","vendor","unknown")
ElementSetAttr("LED68","vendor_part_number","unknown")
ChangePinName("LED68", 2, "K")
ChangePinName("LED68", 1, "A")
ElementList(Need,"LED66","T1.75_LED.fp","unknown")
ElementSetAttr("LED66","device","LED")
ElementSetAttr("LED66","manufacturer","unknown")
ElementSetAttr("LED66","manufacturer_part_number","unknown")
ElementSetAttr("LED66","vendor","unknown")
ElementSetAttr("LED66","vendor_part_number","unknown")
ChangePinName("LED66", 2, "K")
ChangePinName("LED66", 1, "A")
ElementList(Need,"LED64","T1.75_LED.fp","unknown")
ElementSetAttr("LED64","device","LED")
ElementSetAttr("LED64","manufacturer","unknown")
ElementSetAttr("LED64","manufacturer_part_number","unknown")
ElementSetAttr("LED64","vendor","unknown")
ElementSetAttr("LED64","vendor_part_number","unknown")
ChangePinName("LED64", 2, "K")
ChangePinName("LED64", 1, "A")
ElementList(Need,"LED5","T1.75_LED.fp","unknown")
ElementSetAttr("LED5","device","LED")
ElementSetAttr("LED5","manufacturer","unknown")
ElementSetAttr("LED5","manufacturer_part_number","unknown")
ElementSetAttr("LED5","vendor","unknown")
ElementSetAttr("LED5","vendor_part_number","unknown")
ChangePinName("LED5", 2, "K")
ChangePinName("LED5", 1, "A")
ElementList(Need,"LED2","T1.75_LED.fp","unknown")
ElementSetAttr("LED2","device","LED")
ElementSetAttr("LED2","manufacturer","unknown")
ElementSetAttr("LED2","manufacturer_part_number","unknown")
ElementSetAttr("LED2","vendor","unknown")
ElementSetAttr("LED2","vendor_part_number","unknown")
ChangePinName("LED2", 2, "K")
ChangePinName("LED2", 1, "A")
ElementList(Need,"LED4","T1.75_LED.fp","unknown")
ElementSetAttr("LED4","device","LED")
ElementSetAttr("LED4","manufacturer","unknown")
ElementSetAttr("LED4","manufacturer_part_number","unknown")
ElementSetAttr("LED4","vendor","unknown")
ElementSetAttr("LED4","vendor_part_number","unknown")
ChangePinName("LED4", 2, "K")
ChangePinName("LED4", 1, "A")
ElementList(Need,"LED8","T1.75_LED.fp","unknown")
ElementSetAttr("LED8","device","LED")
ElementSetAttr("LED8","manufacturer","unknown")
ElementSetAttr("LED8","manufacturer_part_number","unknown")
ElementSetAttr("LED8","vendor","unknown")
ElementSetAttr("LED8","vendor_part_number","unknown")
ChangePinName("LED8", 2, "K")
ChangePinName("LED8", 1, "A")
ElementList(Need,"LED1","T1.75_LED.fp","unknown")
ElementSetAttr("LED1","device","LED")
ElementSetAttr("LED1","manufacturer","unknown")
ElementSetAttr("LED1","manufacturer_part_number","unknown")
ElementSetAttr("LED1","vendor","unknown")
ElementSetAttr("LED1","vendor_part_number","unknown")
ChangePinName("LED1", 2, "K")
ChangePinName("LED1", 1, "A")
ElementList(Need,"LED3","T1.75_LED.fp","unknown")
ElementSetAttr("LED3","device","LED")
ElementSetAttr("LED3","manufacturer","unknown")
ElementSetAttr("LED3","manufacturer_part_number","unknown")
ElementSetAttr("LED3","vendor","unknown")
ElementSetAttr("LED3","vendor_part_number","unknown")
ChangePinName("LED3", 2, "K")
ChangePinName("LED3", 1, "A")
ElementList(Need,"LED6","T1.75_LED.fp","unknown")
ElementSetAttr("LED6","device","LED")
ElementSetAttr("LED6","manufacturer","unknown")
ElementSetAttr("LED6","manufacturer_part_number","unknown")
ElementSetAttr("LED6","vendor","unknown")
ElementSetAttr("LED6","vendor_part_number","unknown")
ChangePinName("LED6", 2, "K")
ChangePinName("LED6", 1, "A")
ElementList(Need,"LED7","T1.75_LED.fp","unknown")
ElementSetAttr("LED7","device","LED")
ElementSetAttr("LED7","manufacturer","unknown")
ElementSetAttr("LED7","manufacturer_part_number","unknown")
ElementSetAttr("LED7","vendor","unknown")
ElementSetAttr("LED7","vendor_part_number","unknown")
ChangePinName("LED7", 2, "K")
ChangePinName("LED7", 1, "A")
ElementList(Need,"LED9","T1.75_LED.fp","unknown")
ElementSetAttr("LED9","device","LED")
ElementSetAttr("LED9","manufacturer","unknown")
ElementSetAttr("LED9","manufacturer_part_number","unknown")
ElementSetAttr("LED9","vendor","unknown")
ElementSetAttr("LED9","vendor_part_number","unknown")
ChangePinName("LED9", 2, "K")
ChangePinName("LED9", 1, "A")
ElementList(Need,"LED11","T1.75_LED.fp","unknown")
ElementSetAttr("LED11","device","LED")
ElementSetAttr("LED11","manufacturer","unknown")
ElementSetAttr("LED11","manufacturer_part_number","unknown")
ElementSetAttr("LED11","vendor","unknown")
ElementSetAttr("LED11","vendor_part_number","unknown")
ChangePinName("LED11", 2, "K")
ChangePinName("LED11", 1, "A")
ElementList(Need,"LED13","T1.75_LED.fp","unknown")
ElementSetAttr("LED13","device","LED")
ElementSetAttr("LED13","manufacturer","unknown")
ElementSetAttr("LED13","manufacturer_part_number","unknown")
ElementSetAttr("LED13","vendor","unknown")
ElementSetAttr("LED13","vendor_part_number","unknown")
ChangePinName("LED13", 2, "K")
ChangePinName("LED13", 1, "A")
ElementList(Need,"LED10","T1.75_LED.fp","unknown")
ElementSetAttr("LED10","device","LED")
ElementSetAttr("LED10","manufacturer","unknown")
ElementSetAttr("LED10","manufacturer_part_number","unknown")
ElementSetAttr("LED10","vendor","unknown")
ElementSetAttr("LED10","vendor_part_number","unknown")
ChangePinName("LED10", 2, "K")
ChangePinName("LED10", 1, "A")
ElementList(Need,"LED12","T1.75_LED.fp","unknown")
ElementSetAttr("LED12","device","LED")
ElementSetAttr("LED12","manufacturer","unknown")
ElementSetAttr("LED12","manufacturer_part_number","unknown")
ElementSetAttr("LED12","vendor","unknown")
ElementSetAttr("LED12","vendor_part_number","unknown")
ChangePinName("LED12", 2, "K")
ChangePinName("LED12", 1, "A")
ElementList(Need,"LED14","T1.75_LED.fp","unknown")
ElementSetAttr("LED14","device","LED")
ElementSetAttr("LED14","manufacturer","unknown")
ElementSetAttr("LED14","manufacturer_part_number","unknown")
ElementSetAttr("LED14","vendor","unknown")
ElementSetAttr("LED14","vendor_part_number","unknown")
ChangePinName("LED14", 2, "K")
ChangePinName("LED14", 1, "A")
ElementList(Done)
