Netlist(Freeze)
Netlist(Clear)
Netlist(Add,CH19,Q43-1)
Netlist(Add,CH19,Q42-1)
Netlist(Add,CH18,Q41-1)
Netlist(Add,CH18,Q40-1)
Netlist(Add,CH17,Q38-1)
Netlist(Add,CH17,Q39-1)
Netlist(Add,CH16,Q37-1)
Netlist(Add,CH16,Q35-1)
Netlist(Add,CH15,Q36-1)
Netlist(Add,CH15,Q34-1)
Netlist(Add,CH14,Q33-1)
Netlist(Add,CH14,Q31-1)
Netlist(Add,CH14,Q32-1)
Netlist(Add,CH13,Q30-1)
Netlist(Add,CH13,Q29-1)
Netlist(Add,CH12,Q28-1)
Netlist(Add,CH12,Q27-1)
Netlist(Add,CH12,Q26-1)
Netlist(Add,CH11,Q25-1)
Netlist(Add,CH11,Q24-1)
Netlist(Add,CH10,Q21-1)
Netlist(Add,CH10,Q23-1)
Netlist(Add,CH10,Q22-1)
Netlist(Add,CH9,Q20-1)
Netlist(Add,CH9,Q19-1)
Netlist(Add,CH8,Q17-1)
Netlist(Add,CH8,Q16-1)
Netlist(Add,CH8,Q15-1)
Netlist(Add,CH7,Q14-1)
Netlist(Add,CH7,Q13-1)
Netlist(Add,CH6,Q12-1)
Netlist(Add,CH6,Q11-1)
Netlist(Add,CH6,Q10-1)
Netlist(Add,CH5,Q9-1)
Netlist(Add,CH5,Q8-1)
Netlist(Add,CH4,Q6-1)
Netlist(Add,CH4,Q7-1)
Netlist(Add,CH4,Q5-1)
Netlist(Add,CH3,Q4-1)
Netlist(Add,CH2,Q3-1)
Netlist(Add,CH2,Q2-1)
Netlist(Add,CH1,Q1-1)
Netlist(Add,GND,Q43-2)
Netlist(Add,GND,Q42-2)
Netlist(Add,GND,Q41-2)
Netlist(Add,GND,Q38-2)
Netlist(Add,GND,Q40-2)
Netlist(Add,GND,Q39-2)
Netlist(Add,GND,Q37-2)
Netlist(Add,GND,Q35-2)
Netlist(Add,GND,Q36-2)
Netlist(Add,GND,Q34-2)
Netlist(Add,GND,Q33-2)
Netlist(Add,GND,Q31-2)
Netlist(Add,GND,Q32-2)
Netlist(Add,GND,Q30-2)
Netlist(Add,GND,Q29-2)
Netlist(Add,GND,Q28-2)
Netlist(Add,GND,Q27-2)
Netlist(Add,GND,Q26-2)
Netlist(Add,GND,Q25-2)
Netlist(Add,GND,Q24-2)
Netlist(Add,GND,Q21-2)
Netlist(Add,GND,Q23-2)
Netlist(Add,GND,Q22-2)
Netlist(Add,GND,Q20-2)
Netlist(Add,GND,Q19-2)
Netlist(Add,GND,Q17-2)
Netlist(Add,GND,Q16-2)
Netlist(Add,GND,Q15-2)
Netlist(Add,GND,Q14-2)
Netlist(Add,GND,Q13-2)
Netlist(Add,GND,Q12-2)
Netlist(Add,GND,Q11-2)
Netlist(Add,GND,Q10-2)
Netlist(Add,GND,Q6-2)
Netlist(Add,GND,Q9-2)
Netlist(Add,GND,Q8-2)
Netlist(Add,GND,Q7-2)
Netlist(Add,GND,Q5-2)
Netlist(Add,GND,Q4-2)
Netlist(Add,GND,Q3-2)
Netlist(Add,GND,Q2-2)
Netlist(Add,GND,Q1-2)
Netlist(Add,GND,C1-1)
Netlist(Add,CH1A,Q1-3)
Netlist(Add,CH1A,LED15-2)
Netlist(Add,unnamed_net91,LED16-2)
Netlist(Add,unnamed_net91,LED15-1)
Netlist(Add,CH2A,Q2-3)
Netlist(Add,CH2A,LED17-2)
Netlist(Add,unnamed_net90,LED18-2)
Netlist(Add,unnamed_net90,LED17-1)
Netlist(Add,CH3A,Q4-3)
Netlist(Add,CH3A,LED19-2)
Netlist(Add,unnamed_net89,LED20-2)
Netlist(Add,unnamed_net89,LED19-1)
Netlist(Add,unnamed_net88,R29-2)
Netlist(Add,unnamed_net88,LED40-1)
Netlist(Add,unnamed_net87,R40-2)
Netlist(Add,unnamed_net87,LED43-1)
Netlist(Add,unnamed_net86,R49-2)
Netlist(Add,unnamed_net86,LED46-1)
Netlist(Add,unnamed_net85,R46-2)
Netlist(Add,unnamed_net85,LED45-1)
Netlist(Add,unnamed_net84,R55-2)
Netlist(Add,unnamed_net84,LED48-1)
Netlist(Add,unnamed_net83,R59-2)
Netlist(Add,unnamed_net83,LED50-1)
Netlist(Add,unnamed_net82,R56-2)
Netlist(Add,unnamed_net82,LED49-1)
Netlist(Add,unnamed_net81,R61-2)
Netlist(Add,unnamed_net81,LED51-1)
Netlist(Add,unnamed_net80,R63-2)
Netlist(Add,unnamed_net80,LED52-1)
Netlist(Add,unnamed_net79,R67-2)
Netlist(Add,unnamed_net79,LED54-1)
Netlist(Add,unnamed_net78,R18-2)
Netlist(Add,unnamed_net78,LED25-1)
Netlist(Add,unnamed_net77,R21-2)
Netlist(Add,unnamed_net77,LED68-1)
Netlist(Add,unnamed_net76,R25-2)
Netlist(Add,unnamed_net76,LED28-1)
Netlist(Add,unnamed_net75,R22-2)
Netlist(Add,unnamed_net75,LED27-1)
Netlist(Add,CH6B,Q12-3)
Netlist(Add,CH6B,LED68-2)
Netlist(Add,CH6B,LED26-2)
Netlist(Add,unnamed_net74,R20-2)
Netlist(Add,unnamed_net74,LED26-1)
Netlist(Add,unnamed_net73,R17-2)
Netlist(Add,unnamed_net73,LED24-1)
Netlist(Add,unnamed_net72,R14-2)
Netlist(Add,unnamed_net72,LED23-1)
Netlist(Add,unnamed_net71,R76-2)
Netlist(Add,unnamed_net71,LED22-1)
Netlist(Add,unnamed_net70,R35-2)
Netlist(Add,unnamed_net70,LED74-1)
Netlist(Add,unnamed_net69,R31-2)
Netlist(Add,unnamed_net69,LED72-1)
Netlist(Add,CH7B,Q14-3)
Netlist(Add,CH7B,LED28-2)
Netlist(Add,CH7B,LED70-2)
Netlist(Add,unnamed_net68,R24-2)
Netlist(Add,unnamed_net68,LED70-1)
Netlist(Add,CH5B,LED24-2)
Netlist(Add,CH5B,Q9-3)
Netlist(Add,CH5B,LED66-2)
Netlist(Add,unnamed_net67,R16-2)
Netlist(Add,unnamed_net67,LED66-1)
Netlist(Add,CH4B,LED22-2)
Netlist(Add,CH4B,Q6-3)
Netlist(Add,CH4B,LED64-2)
Netlist(Add,unnamed_net66,R13-2)
Netlist(Add,unnamed_net66,LED64-1)
Netlist(Add,unnamed_net65,R48-2)
Netlist(Add,unnamed_net65,LED78-1)
Netlist(Add,unnamed_net64,R42-2)
Netlist(Add,unnamed_net64,LED76-1)
Netlist(Add,CH15B,Q36-3)
Netlist(Add,CH15B,LED54-2)
Netlist(Add,CH15B,LED86-2)
Netlist(Add,unnamed_net63,R66-2)
Netlist(Add,unnamed_net63,LED86-1)
Netlist(Add,unnamed_net62,Q33-3)
Netlist(Add,unnamed_net62,LED52-2)
Netlist(Add,unnamed_net62,LED84-2)
Netlist(Add,unnamed_net61,R62-2)
Netlist(Add,unnamed_net61,LED84-1)
Netlist(Add,unnamed_net60,Q30-3)
Netlist(Add,unnamed_net60,LED50-2)
Netlist(Add,unnamed_net60,LED82-2)
Netlist(Add,unnamed_net59,R58-2)
Netlist(Add,unnamed_net59,LED82-1)
Netlist(Add,unnamed_net58,R54-2)
Netlist(Add,unnamed_net58,LED80-1)
Netlist(Add,CH2B,Q3-3)
Netlist(Add,CH2B,LED2-2)
Netlist(Add,CH4A,Q7-3)
Netlist(Add,CH4A,LED4-2)
Netlist(Add,CH8A,Q15-3)
Netlist(Add,CH8A,LED8-2)
Netlist(Add,CH6A,Q11-3)
Netlist(Add,CH6A,LED6-2)
Netlist(Add,CH10A,Q21-3)
Netlist(Add,CH10A,LED10-2)
Netlist(Add,unnamed_net57,Q28-3)
Netlist(Add,unnamed_net57,LED12-2)
Netlist(Add,unnamed_net56,Q31-3)
Netlist(Add,unnamed_net56,LED14-2)
Netlist(Add,unnamed_net55,LED6-1)
Netlist(Add,unnamed_net55,LED5-2)
Netlist(Add,unnamed_net54,R3-2)
Netlist(Add,unnamed_net54,LED5-1)
Netlist(Add,unnamed_net53,LED2-1)
Netlist(Add,unnamed_net53,LED1-2)
Netlist(Add,unnamed_net52,LED4-1)
Netlist(Add,unnamed_net52,LED3-2)
Netlist(Add,unnamed_net51,LED8-1)
Netlist(Add,unnamed_net51,LED7-2)
Netlist(Add,unnamed_net50,R4-2)
Netlist(Add,unnamed_net50,LED7-1)
Netlist(Add,unnamed_net49,LED10-1)
Netlist(Add,unnamed_net49,LED9-2)
Netlist(Add,unnamed_net48,R5-2)
Netlist(Add,unnamed_net48,LED9-1)
Netlist(Add,unnamed_net47,LED12-1)
Netlist(Add,unnamed_net47,LED11-2)
Netlist(Add,unnamed_net46,R6-2)
Netlist(Add,unnamed_net46,LED11-1)
Netlist(Add,unnamed_net45,LED14-1)
Netlist(Add,unnamed_net45,LED13-2)
Netlist(Add,unnamed_net44,R7-2)
Netlist(Add,unnamed_net44,LED13-1)
Netlist(Add,unnamed_net43,R44-2)
Netlist(Add,unnamed_net43,LED77-1)
Netlist(Add,unnamed_net42,R39-2)
Netlist(Add,unnamed_net42,LED75-1)
Netlist(Add,unnamed_net41,R34-2)
Netlist(Add,unnamed_net41,LED73-1)
Netlist(Add,unnamed_net40,R28-2)
Netlist(Add,unnamed_net40,LED71-1)
Netlist(Add,CH7A,Q13-3)
Netlist(Add,CH7A,LED27-2)
Netlist(Add,CH7A,LED69-2)
Netlist(Add,unnamed_net39,R23-2)
Netlist(Add,unnamed_net39,LED69-1)
Netlist(Add,CH6C,Q10-3)
Netlist(Add,CH6C,LED25-2)
Netlist(Add,CH6C,LED67-2)
Netlist(Add,unnamed_net38,R19-2)
Netlist(Add,unnamed_net38,LED67-1)
Netlist(Add,CH5A,Q8-3)
Netlist(Add,CH5A,LED23-2)
Netlist(Add,CH5A,LED65-2)
Netlist(Add,unnamed_net37,R15-2)
Netlist(Add,unnamed_net37,LED65-1)
Netlist(Add,CH4C,Q5-3)
Netlist(Add,CH4C,LED21-2)
Netlist(Add,CH4C,LED63-2)
Netlist(Add,unnamed_net36,R64-2)
Netlist(Add,unnamed_net36,LED85-1)
Netlist(Add,unnamed_net35,Q32-3)
Netlist(Add,unnamed_net35,LED51-2)
Netlist(Add,unnamed_net35,LED83-2)
Netlist(Add,unnamed_net34,R60-2)
Netlist(Add,unnamed_net34,LED83-1)
Netlist(Add,CH13A,Q29-3)
Netlist(Add,CH13A,LED49-2)
Netlist(Add,CH13A,LED81-2)
Netlist(Add,unnamed_net33,R57-2)
Netlist(Add,unnamed_net33,LED81-1)
Netlist(Add,unnamed_net32,R51-2)
Netlist(Add,unnamed_net32,LED79-1)
Netlist(Add,unnamed_net31,LED3-1)
Netlist(Add,unnamed_net31,R2-2)
Netlist(Add,unnamed_net30,LED1-1)
Netlist(Add,unnamed_net30,R1-2)
Netlist(Add,unnamed_net29,LED63-1)
Netlist(Add,unnamed_net29,R12-2)
Netlist(Add,unnamed_net28,LED21-1)
Netlist(Add,unnamed_net28,R11-2)
Netlist(Add,unnamed_net27,LED20-1)
Netlist(Add,unnamed_net27,R10-2)
Netlist(Add,unnamed_net26,LED18-1)
Netlist(Add,unnamed_net26,R9-2)
Netlist(Add,P5VA,C1-2)
Netlist(Add,P5VA,R75-1)
Netlist(Add,P5VA,R73-1)
Netlist(Add,P5VA,R71-1)
Netlist(Add,P5VA,R69-1)
Netlist(Add,P5VA,R74-1)
Netlist(Add,P5VA,R72-1)
Netlist(Add,P5VA,R70-1)
Netlist(Add,P5VA,R68-1)
Netlist(Add,P5VA,R67-1)
Netlist(Add,P5VA,R66-1)
Netlist(Add,P5VA,R65-1)
Netlist(Add,P5VA,R64-1)
Netlist(Add,P5VA,R63-1)
Netlist(Add,P5VA,R62-1)
Netlist(Add,P5VA,R7-1)
Netlist(Add,P5VA,R61-1)
Netlist(Add,P5VA,R60-1)
Netlist(Add,P5VA,R59-1)
Netlist(Add,P5VA,R58-1)
Netlist(Add,P5VA,R57-1)
Netlist(Add,P5VA,R56-1)
Netlist(Add,P5VA,R52-1)
Netlist(Add,P5VA,R51-1)
Netlist(Add,P5VA,R55-1)
Netlist(Add,P5VA,R6-1)
Netlist(Add,P5VA,R53-1)
Netlist(Add,P5VA,R54-1)
Netlist(Add,P5VA,R50-1)
Netlist(Add,P5VA,R49-1)
Netlist(Add,P5VA,R48-1)
Netlist(Add,P5VA,R47-1)
Netlist(Add,P5VA,R46-1)
Netlist(Add,P5VA,R45-1)
Netlist(Add,P5VA,R44-1)
Netlist(Add,P5VA,R5-1)
Netlist(Add,P5VA,R43-1)
Netlist(Add,P5VA,R42-1)
Netlist(Add,P5VA,R39-1)
Netlist(Add,P5VA,R41-1)
Netlist(Add,P5VA,R40-1)
Netlist(Add,P5VA,R26-1)
Netlist(Add,P5VA,R27-1)
Netlist(Add,P5VA,R25-1)
Netlist(Add,P5VA,R34-1)
Netlist(Add,P5VA,R35-1)
Netlist(Add,P5VA,R36-1)
Netlist(Add,P5VA,R38-1)
Netlist(Add,P5VA,R37-1)
Netlist(Add,P5VA,R33-1)
Netlist(Add,P5VA,R32-1)
Netlist(Add,P5VA,R31-1)
Netlist(Add,P5VA,R30-1)
Netlist(Add,P5VA,R29-1)
Netlist(Add,P5VA,R4-1)
Netlist(Add,P5VA,R28-1)
Netlist(Add,P5VA,R24-1)
Netlist(Add,P5VA,R23-1)
Netlist(Add,P5VA,R22-1)
Netlist(Add,P5VA,R20-1)
Netlist(Add,P5VA,R3-1)
Netlist(Add,P5VA,R21-1)
Netlist(Add,P5VA,R19-1)
Netlist(Add,P5VA,R18-1)
Netlist(Add,P5VA,R17-1)
Netlist(Add,P5VA,R16-1)
Netlist(Add,P5VA,R15-1)
Netlist(Add,P5VA,R14-1)
Netlist(Add,P5VA,R76-1)
Netlist(Add,P5VA,R13-1)
Netlist(Add,P5VA,R2-1)
Netlist(Add,P5VA,R1-1)
Netlist(Add,P5VA,R12-1)
Netlist(Add,P5VA,R11-1)
Netlist(Add,P5VA,R10-1)
Netlist(Add,P5VA,R9-1)
Netlist(Add,P5VA,R8-1)
Netlist(Add,unnamed_net25,LED16-1)
Netlist(Add,unnamed_net25,R8-2)
Netlist(Add,CH19A,Q42-3)
Netlist(Add,CH19A,LED61-2)
Netlist(Add,unnamed_net24,R74-2)
Netlist(Add,unnamed_net24,LED61-1)
Netlist(Add,CH18A,Q40-3)
Netlist(Add,CH18A,LED59-2)
Netlist(Add,unnamed_net23,R72-2)
Netlist(Add,unnamed_net23,LED59-1)
Netlist(Add,CH17A,Q38-3)
Netlist(Add,CH17A,LED57-2)
Netlist(Add,unnamed_net22,R70-2)
Netlist(Add,unnamed_net22,LED57-1)
Netlist(Add,CH16A,Q35-3)
Netlist(Add,CH16A,LED55-2)
Netlist(Add,unnamed_net21,R68-2)
Netlist(Add,unnamed_net21,LED55-1)
Netlist(Add,CH15A,Q34-3)
Netlist(Add,CH15A,LED85-2)
Netlist(Add,CH15A,LED53-2)
Netlist(Add,unnamed_net20,R65-2)
Netlist(Add,unnamed_net20,LED53-1)
Netlist(Add,CH19B,Q43-3)
Netlist(Add,CH19B,LED62-2)
Netlist(Add,unnamed_net19,R75-2)
Netlist(Add,unnamed_net19,LED62-1)
Netlist(Add,CH18B,Q41-3)
Netlist(Add,CH18B,LED60-2)
Netlist(Add,unnamed_net18,R73-2)
Netlist(Add,unnamed_net18,LED60-1)
Netlist(Add,CH17B,Q39-3)
Netlist(Add,CH17B,LED58-2)
Netlist(Add,unnamed_net17,R71-2)
Netlist(Add,unnamed_net17,LED58-1)
Netlist(Add,CH16B,Q37-3)
Netlist(Add,CH16B,LED56-2)
Netlist(Add,unnamed_net16,R69-2)
Netlist(Add,unnamed_net16,LED56-1)
Netlist(Add,unnamed_net15,R50-2)
Netlist(Add,unnamed_net15,LED47-1)
Netlist(Add,unnamed_net14,R33-2)
Netlist(Add,unnamed_net14,LED41-1)
Netlist(Add,unnamed_net13,R27-2)
Netlist(Add,unnamed_net13,LED39-1)
Netlist(Add,unnamed_net12,R43-2)
Netlist(Add,unnamed_net12,LED44-1)
Netlist(Add,unnamed_net11,R36-2)
Netlist(Add,unnamed_net11,LED42-1)
Netlist(Add,CH12C,Q26-3)
Netlist(Add,CH12C,LED79-2)
Netlist(Add,CH12C,LED47-2)
Netlist(Add,CH12C,LED37-2)
Netlist(Add,unnamed_net10,R52-2)
Netlist(Add,unnamed_net10,LED37-1)
Netlist(Add,CH11A,Q24-3)
Netlist(Add,CH11A,LED45-2)
Netlist(Add,CH11A,LED77-2)
Netlist(Add,CH11A,LED35-2)
Netlist(Add,unnamed_net9,R45-2)
Netlist(Add,unnamed_net9,LED35-1)
Netlist(Add,CH10B,Q22-3)
Netlist(Add,CH10B,LED43-2)
Netlist(Add,CH10B,LED75-2)
Netlist(Add,CH10B,LED33-2)
Netlist(Add,unnamed_net8,R38-2)
Netlist(Add,unnamed_net8,LED33-1)
Netlist(Add,CH9A,Q19-3)
Netlist(Add,CH9A,LED41-2)
Netlist(Add,CH9A,LED73-2)
Netlist(Add,CH9A,LED31-2)
Netlist(Add,unnamed_net7,R32-2)
Netlist(Add,unnamed_net7,LED31-1)
Netlist(Add,CH8B,Q16-3)
Netlist(Add,CH8B,LED71-2)
Netlist(Add,CH8B,LED39-2)
Netlist(Add,CH8B,LED29-2)
Netlist(Add,unnamed_net6,R26-2)
Netlist(Add,unnamed_net6,LED29-1)
Netlist(Add,CH12B,Q27-3)
Netlist(Add,CH12B,LED48-2)
Netlist(Add,CH12B,LED80-2)
Netlist(Add,CH12B,LED38-2)
Netlist(Add,unnamed_net5,R53-2)
Netlist(Add,unnamed_net5,LED38-1)
Netlist(Add,CH11B,Q25-3)
Netlist(Add,CH11B,LED46-2)
Netlist(Add,CH11B,LED78-2)
Netlist(Add,CH11B,LED36-2)
Netlist(Add,unnamed_net4,R47-2)
Netlist(Add,unnamed_net4,LED36-1)
Netlist(Add,CH10C,LED44-2)
Netlist(Add,CH10C,Q23-3)
Netlist(Add,CH10C,LED76-2)
Netlist(Add,CH10C,LED34-2)
Netlist(Add,unnamed_net3,R41-2)
Netlist(Add,unnamed_net3,LED34-1)
Netlist(Add,CH9B,Q20-3)
Netlist(Add,CH9B,LED42-2)
Netlist(Add,CH9B,LED74-2)
Netlist(Add,CH9B,LED32-2)
Netlist(Add,unnamed_net2,R37-2)
Netlist(Add,unnamed_net2,LED32-1)
Netlist(Add,CH8C,Q17-3)
Netlist(Add,CH8C,LED72-2)
Netlist(Add,CH8C,LED40-2)
Netlist(Add,CH8C,LED30-2)
Netlist(Add,unnamed_net1,R30-2)
Netlist(Add,unnamed_net1,LED30-1)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"Q43","SOT23.fp","unknown")
ElementSetAttr("Q43","device","NMOS_TRANSISTOR")
ElementSetAttr("Q43","manufacturer","unknown")
ElementSetAttr("Q43","manufacturer_part_number","unknown")
ElementSetAttr("Q43","vendor","unknown")
ElementSetAttr("Q43","vendor_part_number","unknown")
ChangePinName("Q43", 2, "S")
ChangePinName("Q43", 3, "D")
ChangePinName("Q43", 1, "G")
ElementList(Need,"Q42","SOT23.fp","unknown")
ElementSetAttr("Q42","device","NMOS_TRANSISTOR")
ElementSetAttr("Q42","manufacturer","unknown")
ElementSetAttr("Q42","manufacturer_part_number","unknown")
ElementSetAttr("Q42","vendor","unknown")
ElementSetAttr("Q42","vendor_part_number","unknown")
ChangePinName("Q42", 2, "S")
ChangePinName("Q42", 3, "D")
ChangePinName("Q42", 1, "G")
ElementList(Need,"Q41","SOT23.fp","unknown")
ElementSetAttr("Q41","device","NMOS_TRANSISTOR")
ElementSetAttr("Q41","manufacturer","unknown")
ElementSetAttr("Q41","manufacturer_part_number","unknown")
ElementSetAttr("Q41","vendor","unknown")
ElementSetAttr("Q41","vendor_part_number","unknown")
ChangePinName("Q41", 2, "S")
ChangePinName("Q41", 3, "D")
ChangePinName("Q41", 1, "G")
ElementList(Need,"Q38","SOT23.fp","unknown")
ElementSetAttr("Q38","device","NMOS_TRANSISTOR")
ElementSetAttr("Q38","manufacturer","unknown")
ElementSetAttr("Q38","manufacturer_part_number","unknown")
ElementSetAttr("Q38","vendor","unknown")
ElementSetAttr("Q38","vendor_part_number","unknown")
ChangePinName("Q38", 2, "S")
ChangePinName("Q38", 3, "D")
ChangePinName("Q38", 1, "G")
ElementList(Need,"Q40","SOT23.fp","unknown")
ElementSetAttr("Q40","device","NMOS_TRANSISTOR")
ElementSetAttr("Q40","manufacturer","unknown")
ElementSetAttr("Q40","manufacturer_part_number","unknown")
ElementSetAttr("Q40","vendor","unknown")
ElementSetAttr("Q40","vendor_part_number","unknown")
ChangePinName("Q40", 2, "S")
ChangePinName("Q40", 3, "D")
ChangePinName("Q40", 1, "G")
ElementList(Need,"Q39","SOT23.fp","unknown")
ElementSetAttr("Q39","device","NMOS_TRANSISTOR")
ElementSetAttr("Q39","manufacturer","unknown")
ElementSetAttr("Q39","manufacturer_part_number","unknown")
ElementSetAttr("Q39","vendor","unknown")
ElementSetAttr("Q39","vendor_part_number","unknown")
ChangePinName("Q39", 2, "S")
ChangePinName("Q39", 3, "D")
ChangePinName("Q39", 1, "G")
ElementList(Need,"Q37","SOT23.fp","unknown")
ElementSetAttr("Q37","device","NMOS_TRANSISTOR")
ElementSetAttr("Q37","manufacturer","unknown")
ElementSetAttr("Q37","manufacturer_part_number","unknown")
ElementSetAttr("Q37","vendor","unknown")
ElementSetAttr("Q37","vendor_part_number","unknown")
ChangePinName("Q37", 2, "S")
ChangePinName("Q37", 3, "D")
ChangePinName("Q37", 1, "G")
ElementList(Need,"Q35","SOT23.fp","unknown")
ElementSetAttr("Q35","device","NMOS_TRANSISTOR")
ElementSetAttr("Q35","manufacturer","unknown")
ElementSetAttr("Q35","manufacturer_part_number","unknown")
ElementSetAttr("Q35","vendor","unknown")
ElementSetAttr("Q35","vendor_part_number","unknown")
ChangePinName("Q35", 2, "S")
ChangePinName("Q35", 3, "D")
ChangePinName("Q35", 1, "G")
ElementList(Need,"Q36","SOT23.fp","unknown")
ElementSetAttr("Q36","device","NMOS_TRANSISTOR")
ElementSetAttr("Q36","manufacturer","unknown")
ElementSetAttr("Q36","manufacturer_part_number","unknown")
ElementSetAttr("Q36","vendor","unknown")
ElementSetAttr("Q36","vendor_part_number","unknown")
ChangePinName("Q36", 2, "S")
ChangePinName("Q36", 3, "D")
ChangePinName("Q36", 1, "G")
ElementList(Need,"Q34","SOT23.fp","unknown")
ElementSetAttr("Q34","device","NMOS_TRANSISTOR")
ElementSetAttr("Q34","manufacturer","unknown")
ElementSetAttr("Q34","manufacturer_part_number","unknown")
ElementSetAttr("Q34","vendor","unknown")
ElementSetAttr("Q34","vendor_part_number","unknown")
ChangePinName("Q34", 2, "S")
ChangePinName("Q34", 3, "D")
ChangePinName("Q34", 1, "G")
ElementList(Need,"Q33","SOT23.fp","unknown")
ElementSetAttr("Q33","device","NMOS_TRANSISTOR")
ElementSetAttr("Q33","manufacturer","unknown")
ElementSetAttr("Q33","manufacturer_part_number","unknown")
ElementSetAttr("Q33","vendor","unknown")
ElementSetAttr("Q33","vendor_part_number","unknown")
ChangePinName("Q33", 2, "S")
ChangePinName("Q33", 3, "D")
ChangePinName("Q33", 1, "G")
ElementList(Need,"Q31","SOT23.fp","unknown")
ElementSetAttr("Q31","device","NMOS_TRANSISTOR")
ElementSetAttr("Q31","manufacturer","unknown")
ElementSetAttr("Q31","manufacturer_part_number","unknown")
ElementSetAttr("Q31","vendor","unknown")
ElementSetAttr("Q31","vendor_part_number","unknown")
ChangePinName("Q31", 2, "S")
ChangePinName("Q31", 3, "D")
ChangePinName("Q31", 1, "G")
ElementList(Need,"Q32","SOT23.fp","unknown")
ElementSetAttr("Q32","device","NMOS_TRANSISTOR")
ElementSetAttr("Q32","manufacturer","unknown")
ElementSetAttr("Q32","manufacturer_part_number","unknown")
ElementSetAttr("Q32","vendor","unknown")
ElementSetAttr("Q32","vendor_part_number","unknown")
ChangePinName("Q32", 2, "S")
ChangePinName("Q32", 3, "D")
ChangePinName("Q32", 1, "G")
ElementList(Need,"Q30","SOT23.fp","unknown")
ElementSetAttr("Q30","device","NMOS_TRANSISTOR")
ElementSetAttr("Q30","manufacturer","unknown")
ElementSetAttr("Q30","manufacturer_part_number","unknown")
ElementSetAttr("Q30","vendor","unknown")
ElementSetAttr("Q30","vendor_part_number","unknown")
ChangePinName("Q30", 2, "S")
ChangePinName("Q30", 3, "D")
ChangePinName("Q30", 1, "G")
ElementList(Need,"Q29","SOT23.fp","unknown")
ElementSetAttr("Q29","device","NMOS_TRANSISTOR")
ElementSetAttr("Q29","manufacturer","unknown")
ElementSetAttr("Q29","manufacturer_part_number","unknown")
ElementSetAttr("Q29","vendor","unknown")
ElementSetAttr("Q29","vendor_part_number","unknown")
ChangePinName("Q29", 2, "S")
ChangePinName("Q29", 3, "D")
ChangePinName("Q29", 1, "G")
ElementList(Need,"Q28","SOT23.fp","unknown")
ElementSetAttr("Q28","device","NMOS_TRANSISTOR")
ElementSetAttr("Q28","manufacturer","unknown")
ElementSetAttr("Q28","manufacturer_part_number","unknown")
ElementSetAttr("Q28","vendor","unknown")
ElementSetAttr("Q28","vendor_part_number","unknown")
ChangePinName("Q28", 2, "S")
ChangePinName("Q28", 3, "D")
ChangePinName("Q28", 1, "G")
ElementList(Need,"Q27","SOT23.fp","unknown")
ElementSetAttr("Q27","device","NMOS_TRANSISTOR")
ElementSetAttr("Q27","manufacturer","unknown")
ElementSetAttr("Q27","manufacturer_part_number","unknown")
ElementSetAttr("Q27","vendor","unknown")
ElementSetAttr("Q27","vendor_part_number","unknown")
ChangePinName("Q27", 2, "S")
ChangePinName("Q27", 3, "D")
ChangePinName("Q27", 1, "G")
ElementList(Need,"Q26","SOT23.fp","unknown")
ElementSetAttr("Q26","device","NMOS_TRANSISTOR")
ElementSetAttr("Q26","manufacturer","unknown")
ElementSetAttr("Q26","manufacturer_part_number","unknown")
ElementSetAttr("Q26","vendor","unknown")
ElementSetAttr("Q26","vendor_part_number","unknown")
ChangePinName("Q26", 2, "S")
ChangePinName("Q26", 3, "D")
ChangePinName("Q26", 1, "G")
ElementList(Need,"Q25","SOT23.fp","unknown")
ElementSetAttr("Q25","device","NMOS_TRANSISTOR")
ElementSetAttr("Q25","manufacturer","unknown")
ElementSetAttr("Q25","manufacturer_part_number","unknown")
ElementSetAttr("Q25","vendor","unknown")
ElementSetAttr("Q25","vendor_part_number","unknown")
ChangePinName("Q25", 2, "S")
ChangePinName("Q25", 3, "D")
ChangePinName("Q25", 1, "G")
ElementList(Need,"Q24","SOT23.fp","unknown")
ElementSetAttr("Q24","device","NMOS_TRANSISTOR")
ElementSetAttr("Q24","manufacturer","unknown")
ElementSetAttr("Q24","manufacturer_part_number","unknown")
ElementSetAttr("Q24","vendor","unknown")
ElementSetAttr("Q24","vendor_part_number","unknown")
ChangePinName("Q24", 2, "S")
ChangePinName("Q24", 3, "D")
ChangePinName("Q24", 1, "G")
ElementList(Need,"Q21","SOT23.fp","unknown")
ElementSetAttr("Q21","device","NMOS_TRANSISTOR")
ElementSetAttr("Q21","manufacturer","unknown")
ElementSetAttr("Q21","manufacturer_part_number","unknown")
ElementSetAttr("Q21","vendor","unknown")
ElementSetAttr("Q21","vendor_part_number","unknown")
ChangePinName("Q21", 2, "S")
ChangePinName("Q21", 3, "D")
ChangePinName("Q21", 1, "G")
ElementList(Need,"Q23","SOT23.fp","unknown")
ElementSetAttr("Q23","device","NMOS_TRANSISTOR")
ElementSetAttr("Q23","manufacturer","unknown")
ElementSetAttr("Q23","manufacturer_part_number","unknown")
ElementSetAttr("Q23","vendor","unknown")
ElementSetAttr("Q23","vendor_part_number","unknown")
ChangePinName("Q23", 2, "S")
ChangePinName("Q23", 3, "D")
ChangePinName("Q23", 1, "G")
ElementList(Need,"Q22","SOT23.fp","unknown")
ElementSetAttr("Q22","device","NMOS_TRANSISTOR")
ElementSetAttr("Q22","manufacturer","unknown")
ElementSetAttr("Q22","manufacturer_part_number","unknown")
ElementSetAttr("Q22","vendor","unknown")
ElementSetAttr("Q22","vendor_part_number","unknown")
ChangePinName("Q22", 2, "S")
ChangePinName("Q22", 3, "D")
ChangePinName("Q22", 1, "G")
ElementList(Need,"Q20","SOT23.fp","unknown")
ElementSetAttr("Q20","device","NMOS_TRANSISTOR")
ElementSetAttr("Q20","manufacturer","unknown")
ElementSetAttr("Q20","manufacturer_part_number","unknown")
ElementSetAttr("Q20","vendor","unknown")
ElementSetAttr("Q20","vendor_part_number","unknown")
ChangePinName("Q20", 2, "S")
ChangePinName("Q20", 3, "D")
ChangePinName("Q20", 1, "G")
ElementList(Need,"Q19","SOT23.fp","unknown")
ElementSetAttr("Q19","device","NMOS_TRANSISTOR")
ElementSetAttr("Q19","manufacturer","unknown")
ElementSetAttr("Q19","manufacturer_part_number","unknown")
ElementSetAttr("Q19","vendor","unknown")
ElementSetAttr("Q19","vendor_part_number","unknown")
ChangePinName("Q19", 2, "S")
ChangePinName("Q19", 3, "D")
ChangePinName("Q19", 1, "G")
ElementList(Need,"Q17","SOT23.fp","unknown")
ElementSetAttr("Q17","device","NMOS_TRANSISTOR")
ElementSetAttr("Q17","manufacturer","unknown")
ElementSetAttr("Q17","manufacturer_part_number","unknown")
ElementSetAttr("Q17","vendor","unknown")
ElementSetAttr("Q17","vendor_part_number","unknown")
ChangePinName("Q17", 2, "S")
ChangePinName("Q17", 3, "D")
ChangePinName("Q17", 1, "G")
ElementList(Need,"Q16","SOT23.fp","unknown")
ElementSetAttr("Q16","device","NMOS_TRANSISTOR")
ElementSetAttr("Q16","manufacturer","unknown")
ElementSetAttr("Q16","manufacturer_part_number","unknown")
ElementSetAttr("Q16","vendor","unknown")
ElementSetAttr("Q16","vendor_part_number","unknown")
ChangePinName("Q16", 2, "S")
ChangePinName("Q16", 3, "D")
ChangePinName("Q16", 1, "G")
ElementList(Need,"Q15","SOT23.fp","unknown")
ElementSetAttr("Q15","device","NMOS_TRANSISTOR")
ElementSetAttr("Q15","manufacturer","unknown")
ElementSetAttr("Q15","manufacturer_part_number","unknown")
ElementSetAttr("Q15","vendor","unknown")
ElementSetAttr("Q15","vendor_part_number","unknown")
ChangePinName("Q15", 2, "S")
ChangePinName("Q15", 3, "D")
ChangePinName("Q15", 1, "G")
ElementList(Need,"Q14","SOT23.fp","unknown")
ElementSetAttr("Q14","device","NMOS_TRANSISTOR")
ElementSetAttr("Q14","manufacturer","unknown")
ElementSetAttr("Q14","manufacturer_part_number","unknown")
ElementSetAttr("Q14","vendor","unknown")
ElementSetAttr("Q14","vendor_part_number","unknown")
ChangePinName("Q14", 2, "S")
ChangePinName("Q14", 3, "D")
ChangePinName("Q14", 1, "G")
ElementList(Need,"Q13","SOT23.fp","unknown")
ElementSetAttr("Q13","device","NMOS_TRANSISTOR")
ElementSetAttr("Q13","manufacturer","unknown")
ElementSetAttr("Q13","manufacturer_part_number","unknown")
ElementSetAttr("Q13","vendor","unknown")
ElementSetAttr("Q13","vendor_part_number","unknown")
ChangePinName("Q13", 2, "S")
ChangePinName("Q13", 3, "D")
ChangePinName("Q13", 1, "G")
ElementList(Need,"Q12","SOT23.fp","unknown")
ElementSetAttr("Q12","device","NMOS_TRANSISTOR")
ElementSetAttr("Q12","manufacturer","unknown")
ElementSetAttr("Q12","manufacturer_part_number","unknown")
ElementSetAttr("Q12","vendor","unknown")
ElementSetAttr("Q12","vendor_part_number","unknown")
ChangePinName("Q12", 2, "S")
ChangePinName("Q12", 3, "D")
ChangePinName("Q12", 1, "G")
ElementList(Need,"Q11","SOT23.fp","unknown")
ElementSetAttr("Q11","device","NMOS_TRANSISTOR")
ElementSetAttr("Q11","manufacturer","unknown")
ElementSetAttr("Q11","manufacturer_part_number","unknown")
ElementSetAttr("Q11","vendor","unknown")
ElementSetAttr("Q11","vendor_part_number","unknown")
ChangePinName("Q11", 2, "S")
ChangePinName("Q11", 3, "D")
ChangePinName("Q11", 1, "G")
ElementList(Need,"Q10","SOT23.fp","unknown")
ElementSetAttr("Q10","device","NMOS_TRANSISTOR")
ElementSetAttr("Q10","manufacturer","unknown")
ElementSetAttr("Q10","manufacturer_part_number","unknown")
ElementSetAttr("Q10","vendor","unknown")
ElementSetAttr("Q10","vendor_part_number","unknown")
ChangePinName("Q10", 2, "S")
ChangePinName("Q10", 3, "D")
ChangePinName("Q10", 1, "G")
ElementList(Need,"Q6","SOT23.fp","unknown")
ElementSetAttr("Q6","device","NMOS_TRANSISTOR")
ElementSetAttr("Q6","manufacturer","unknown")
ElementSetAttr("Q6","manufacturer_part_number","unknown")
ElementSetAttr("Q6","vendor","unknown")
ElementSetAttr("Q6","vendor_part_number","unknown")
ChangePinName("Q6", 2, "S")
ChangePinName("Q6", 3, "D")
ChangePinName("Q6", 1, "G")
ElementList(Need,"Q9","SOT23.fp","unknown")
ElementSetAttr("Q9","device","NMOS_TRANSISTOR")
ElementSetAttr("Q9","manufacturer","unknown")
ElementSetAttr("Q9","manufacturer_part_number","unknown")
ElementSetAttr("Q9","vendor","unknown")
ElementSetAttr("Q9","vendor_part_number","unknown")
ChangePinName("Q9", 2, "S")
ChangePinName("Q9", 3, "D")
ChangePinName("Q9", 1, "G")
ElementList(Need,"Q8","SOT23.fp","unknown")
ElementSetAttr("Q8","device","NMOS_TRANSISTOR")
ElementSetAttr("Q8","manufacturer","unknown")
ElementSetAttr("Q8","manufacturer_part_number","unknown")
ElementSetAttr("Q8","vendor","unknown")
ElementSetAttr("Q8","vendor_part_number","unknown")
ChangePinName("Q8", 2, "S")
ChangePinName("Q8", 3, "D")
ChangePinName("Q8", 1, "G")
ElementList(Need,"Q7","SOT23.fp","unknown")
ElementSetAttr("Q7","device","NMOS_TRANSISTOR")
ElementSetAttr("Q7","manufacturer","unknown")
ElementSetAttr("Q7","manufacturer_part_number","unknown")
ElementSetAttr("Q7","vendor","unknown")
ElementSetAttr("Q7","vendor_part_number","unknown")
ChangePinName("Q7", 2, "S")
ChangePinName("Q7", 3, "D")
ChangePinName("Q7", 1, "G")
ElementList(Need,"Q5","SOT23.fp","unknown")
ElementSetAttr("Q5","device","NMOS_TRANSISTOR")
ElementSetAttr("Q5","manufacturer","unknown")
ElementSetAttr("Q5","manufacturer_part_number","unknown")
ElementSetAttr("Q5","vendor","unknown")
ElementSetAttr("Q5","vendor_part_number","unknown")
ChangePinName("Q5", 2, "S")
ChangePinName("Q5", 3, "D")
ChangePinName("Q5", 1, "G")
ElementList(Need,"Q4","SOT23.fp","unknown")
ElementSetAttr("Q4","device","NMOS_TRANSISTOR")
ElementSetAttr("Q4","manufacturer","unknown")
ElementSetAttr("Q4","manufacturer_part_number","unknown")
ElementSetAttr("Q4","vendor","unknown")
ElementSetAttr("Q4","vendor_part_number","unknown")
ChangePinName("Q4", 2, "S")
ChangePinName("Q4", 3, "D")
ChangePinName("Q4", 1, "G")
ElementList(Need,"Q3","SOT23.fp","unknown")
ElementSetAttr("Q3","device","NMOS_TRANSISTOR")
ElementSetAttr("Q3","manufacturer","unknown")
ElementSetAttr("Q3","manufacturer_part_number","unknown")
ElementSetAttr("Q3","vendor","unknown")
ElementSetAttr("Q3","vendor_part_number","unknown")
ChangePinName("Q3", 2, "S")
ChangePinName("Q3", 3, "D")
ChangePinName("Q3", 1, "G")
ElementList(Need,"Q2","SOT23.fp","unknown")
ElementSetAttr("Q2","device","NMOS_TRANSISTOR")
ElementSetAttr("Q2","manufacturer","unknown")
ElementSetAttr("Q2","manufacturer_part_number","unknown")
ElementSetAttr("Q2","vendor","unknown")
ElementSetAttr("Q2","vendor_part_number","unknown")
ChangePinName("Q2", 2, "S")
ChangePinName("Q2", 3, "D")
ChangePinName("Q2", 1, "G")
ElementList(Need,"Q1","SOT23.fp","unknown")
ElementSetAttr("Q1","device","NMOS_TRANSISTOR")
ElementSetAttr("Q1","manufacturer","unknown")
ElementSetAttr("Q1","manufacturer_part_number","unknown")
ElementSetAttr("Q1","vendor","unknown")
ElementSetAttr("Q1","vendor_part_number","unknown")
ChangePinName("Q1", 2, "S")
ChangePinName("Q1", 3, "D")
ChangePinName("Q1", 1, "G")
ElementList(Need,"C1","0805","0.1uF")
ElementSetAttr("C1","device","CAPACITOR")
ElementSetAttr("C1","manufacturer","unknown")
ElementSetAttr("C1","manufacturer_part_number","unknown")
ElementSetAttr("C1","vendor","unknown")
ElementSetAttr("C1","vendor_part_number","unknown")
ChangePinName("C1", 2, "2")
ChangePinName("C1", 1, "1")
ElementList(Need,"LED16","T1.75_LED.fp","unknown")
ElementSetAttr("LED16","device","LED")
ElementSetAttr("LED16","manufacturer","unknown")
ElementSetAttr("LED16","manufacturer_part_number","unknown")
ElementSetAttr("LED16","vendor","unknown")
ElementSetAttr("LED16","vendor_part_number","unknown")
ChangePinName("LED16", 2, "K")
ChangePinName("LED16", 1, "A")
ElementList(Need,"LED15","T1.75_LED.fp","unknown")
ElementSetAttr("LED15","device","LED")
ElementSetAttr("LED15","manufacturer","unknown")
ElementSetAttr("LED15","manufacturer_part_number","unknown")
ElementSetAttr("LED15","vendor","unknown")
ElementSetAttr("LED15","vendor_part_number","unknown")
ChangePinName("LED15", 2, "K")
ChangePinName("LED15", 1, "A")
ElementList(Need,"LED18","T1.75_LED.fp","unknown")
ElementSetAttr("LED18","device","LED")
ElementSetAttr("LED18","manufacturer","unknown")
ElementSetAttr("LED18","manufacturer_part_number","unknown")
ElementSetAttr("LED18","vendor","unknown")
ElementSetAttr("LED18","vendor_part_number","unknown")
ChangePinName("LED18", 2, "K")
ChangePinName("LED18", 1, "A")
ElementList(Need,"LED17","T1.75_LED.fp","unknown")
ElementSetAttr("LED17","device","LED")
ElementSetAttr("LED17","manufacturer","unknown")
ElementSetAttr("LED17","manufacturer_part_number","unknown")
ElementSetAttr("LED17","vendor","unknown")
ElementSetAttr("LED17","vendor_part_number","unknown")
ChangePinName("LED17", 2, "K")
ChangePinName("LED17", 1, "A")
ElementList(Need,"LED20","T1.75_LED.fp","unknown")
ElementSetAttr("LED20","device","LED")
ElementSetAttr("LED20","manufacturer","unknown")
ElementSetAttr("LED20","manufacturer_part_number","unknown")
ElementSetAttr("LED20","vendor","unknown")
ElementSetAttr("LED20","vendor_part_number","unknown")
ChangePinName("LED20", 2, "K")
ChangePinName("LED20", 1, "A")
ElementList(Need,"LED19","T1.75_LED.fp","unknown")
ElementSetAttr("LED19","device","LED")
ElementSetAttr("LED19","manufacturer","unknown")
ElementSetAttr("LED19","manufacturer_part_number","unknown")
ElementSetAttr("LED19","vendor","unknown")
ElementSetAttr("LED19","vendor_part_number","unknown")
ChangePinName("LED19", 2, "K")
ChangePinName("LED19", 1, "A")
ElementList(Need,"R75","0805","1K")
ElementSetAttr("R75","device","RESISTOR")
ElementSetAttr("R75","manufacturer","unknown")
ElementSetAttr("R75","manufacturer_part_number","unknown")
ElementSetAttr("R75","vendor","unknown")
ElementSetAttr("R75","vendor_part_number","unknown")
ChangePinName("R75", 1, "1")
ChangePinName("R75", 2, "2")
ElementList(Need,"R73","0805","1K")
ElementSetAttr("R73","device","RESISTOR")
ElementSetAttr("R73","manufacturer","unknown")
ElementSetAttr("R73","manufacturer_part_number","unknown")
ElementSetAttr("R73","vendor","unknown")
ElementSetAttr("R73","vendor_part_number","unknown")
ChangePinName("R73", 1, "1")
ChangePinName("R73", 2, "2")
ElementList(Need,"R71","0805","1K")
ElementSetAttr("R71","device","RESISTOR")
ElementSetAttr("R71","manufacturer","unknown")
ElementSetAttr("R71","manufacturer_part_number","unknown")
ElementSetAttr("R71","vendor","unknown")
ElementSetAttr("R71","vendor_part_number","unknown")
ChangePinName("R71", 1, "1")
ChangePinName("R71", 2, "2")
ElementList(Need,"R69","0805","1K")
ElementSetAttr("R69","device","RESISTOR")
ElementSetAttr("R69","manufacturer","unknown")
ElementSetAttr("R69","manufacturer_part_number","unknown")
ElementSetAttr("R69","vendor","unknown")
ElementSetAttr("R69","vendor_part_number","unknown")
ChangePinName("R69", 1, "1")
ChangePinName("R69", 2, "2")
ElementList(Need,"R74","0805","1K")
ElementSetAttr("R74","device","RESISTOR")
ElementSetAttr("R74","manufacturer","unknown")
ElementSetAttr("R74","manufacturer_part_number","unknown")
ElementSetAttr("R74","vendor","unknown")
ElementSetAttr("R74","vendor_part_number","unknown")
ChangePinName("R74", 1, "1")
ChangePinName("R74", 2, "2")
ElementList(Need,"R72","0805","1K")
ElementSetAttr("R72","device","RESISTOR")
ElementSetAttr("R72","manufacturer","unknown")
ElementSetAttr("R72","manufacturer_part_number","unknown")
ElementSetAttr("R72","vendor","unknown")
ElementSetAttr("R72","vendor_part_number","unknown")
ChangePinName("R72", 1, "1")
ChangePinName("R72", 2, "2")
ElementList(Need,"R70","0805","1K")
ElementSetAttr("R70","device","RESISTOR")
ElementSetAttr("R70","manufacturer","unknown")
ElementSetAttr("R70","manufacturer_part_number","unknown")
ElementSetAttr("R70","vendor","unknown")
ElementSetAttr("R70","vendor_part_number","unknown")
ChangePinName("R70", 1, "1")
ChangePinName("R70", 2, "2")
ElementList(Need,"R68","0805","1K")
ElementSetAttr("R68","device","RESISTOR")
ElementSetAttr("R68","manufacturer","unknown")
ElementSetAttr("R68","manufacturer_part_number","unknown")
ElementSetAttr("R68","vendor","unknown")
ElementSetAttr("R68","vendor_part_number","unknown")
ChangePinName("R68", 1, "1")
ChangePinName("R68", 2, "2")
ElementList(Need,"R67","0805","1K")
ElementSetAttr("R67","device","RESISTOR")
ElementSetAttr("R67","manufacturer","unknown")
ElementSetAttr("R67","manufacturer_part_number","unknown")
ElementSetAttr("R67","vendor","unknown")
ElementSetAttr("R67","vendor_part_number","unknown")
ChangePinName("R67", 1, "1")
ChangePinName("R67", 2, "2")
ElementList(Need,"R66","0805","1K")
ElementSetAttr("R66","device","RESISTOR")
ElementSetAttr("R66","manufacturer","unknown")
ElementSetAttr("R66","manufacturer_part_number","unknown")
ElementSetAttr("R66","vendor","unknown")
ElementSetAttr("R66","vendor_part_number","unknown")
ChangePinName("R66", 1, "1")
ChangePinName("R66", 2, "2")
ElementList(Need,"R65","0805","1K")
ElementSetAttr("R65","device","RESISTOR")
ElementSetAttr("R65","manufacturer","unknown")
ElementSetAttr("R65","manufacturer_part_number","unknown")
ElementSetAttr("R65","vendor","unknown")
ElementSetAttr("R65","vendor_part_number","unknown")
ChangePinName("R65", 1, "1")
ChangePinName("R65", 2, "2")
ElementList(Need,"R64","0805","1K")
ElementSetAttr("R64","device","RESISTOR")
ElementSetAttr("R64","manufacturer","unknown")
ElementSetAttr("R64","manufacturer_part_number","unknown")
ElementSetAttr("R64","vendor","unknown")
ElementSetAttr("R64","vendor_part_number","unknown")
ChangePinName("R64", 1, "1")
ChangePinName("R64", 2, "2")
ElementList(Need,"R63","0805","1K")
ElementSetAttr("R63","device","RESISTOR")
ElementSetAttr("R63","manufacturer","unknown")
ElementSetAttr("R63","manufacturer_part_number","unknown")
ElementSetAttr("R63","vendor","unknown")
ElementSetAttr("R63","vendor_part_number","unknown")
ChangePinName("R63", 1, "1")
ChangePinName("R63", 2, "2")
ElementList(Need,"R62","0805","1K")
ElementSetAttr("R62","device","RESISTOR")
ElementSetAttr("R62","manufacturer","unknown")
ElementSetAttr("R62","manufacturer_part_number","unknown")
ElementSetAttr("R62","vendor","unknown")
ElementSetAttr("R62","vendor_part_number","unknown")
ChangePinName("R62", 1, "1")
ChangePinName("R62", 2, "2")
ElementList(Need,"R7","0805","1K")
ElementSetAttr("R7","device","RESISTOR")
ElementSetAttr("R7","manufacturer","unknown")
ElementSetAttr("R7","manufacturer_part_number","unknown")
ElementSetAttr("R7","vendor","unknown")
ElementSetAttr("R7","vendor_part_number","unknown")
ChangePinName("R7", 1, "1")
ChangePinName("R7", 2, "2")
ElementList(Need,"R61","0805","1K")
ElementSetAttr("R61","device","RESISTOR")
ElementSetAttr("R61","manufacturer","unknown")
ElementSetAttr("R61","manufacturer_part_number","unknown")
ElementSetAttr("R61","vendor","unknown")
ElementSetAttr("R61","vendor_part_number","unknown")
ChangePinName("R61", 1, "1")
ChangePinName("R61", 2, "2")
ElementList(Need,"R60","0805","1K")
ElementSetAttr("R60","device","RESISTOR")
ElementSetAttr("R60","manufacturer","unknown")
ElementSetAttr("R60","manufacturer_part_number","unknown")
ElementSetAttr("R60","vendor","unknown")
ElementSetAttr("R60","vendor_part_number","unknown")
ChangePinName("R60", 1, "1")
ChangePinName("R60", 2, "2")
ElementList(Need,"R59","0805","1K")
ElementSetAttr("R59","device","RESISTOR")
ElementSetAttr("R59","manufacturer","unknown")
ElementSetAttr("R59","manufacturer_part_number","unknown")
ElementSetAttr("R59","vendor","unknown")
ElementSetAttr("R59","vendor_part_number","unknown")
ChangePinName("R59", 1, "1")
ChangePinName("R59", 2, "2")
ElementList(Need,"R58","0805","1K")
ElementSetAttr("R58","device","RESISTOR")
ElementSetAttr("R58","manufacturer","unknown")
ElementSetAttr("R58","manufacturer_part_number","unknown")
ElementSetAttr("R58","vendor","unknown")
ElementSetAttr("R58","vendor_part_number","unknown")
ChangePinName("R58", 1, "1")
ChangePinName("R58", 2, "2")
ElementList(Need,"R57","0805","1K")
ElementSetAttr("R57","device","RESISTOR")
ElementSetAttr("R57","manufacturer","unknown")
ElementSetAttr("R57","manufacturer_part_number","unknown")
ElementSetAttr("R57","vendor","unknown")
ElementSetAttr("R57","vendor_part_number","unknown")
ChangePinName("R57", 1, "1")
ChangePinName("R57", 2, "2")
ElementList(Need,"R56","0805","1K")
ElementSetAttr("R56","device","RESISTOR")
ElementSetAttr("R56","manufacturer","unknown")
ElementSetAttr("R56","manufacturer_part_number","unknown")
ElementSetAttr("R56","vendor","unknown")
ElementSetAttr("R56","vendor_part_number","unknown")
ChangePinName("R56", 1, "1")
ChangePinName("R56", 2, "2")
ElementList(Need,"R52","0805","1K")
ElementSetAttr("R52","device","RESISTOR")
ElementSetAttr("R52","manufacturer","unknown")
ElementSetAttr("R52","manufacturer_part_number","unknown")
ElementSetAttr("R52","vendor","unknown")
ElementSetAttr("R52","vendor_part_number","unknown")
ChangePinName("R52", 1, "1")
ChangePinName("R52", 2, "2")
ElementList(Need,"R51","0805","1K")
ElementSetAttr("R51","device","RESISTOR")
ElementSetAttr("R51","manufacturer","unknown")
ElementSetAttr("R51","manufacturer_part_number","unknown")
ElementSetAttr("R51","vendor","unknown")
ElementSetAttr("R51","vendor_part_number","unknown")
ChangePinName("R51", 1, "1")
ChangePinName("R51", 2, "2")
ElementList(Need,"R55","0805","1K")
ElementSetAttr("R55","device","RESISTOR")
ElementSetAttr("R55","manufacturer","unknown")
ElementSetAttr("R55","manufacturer_part_number","unknown")
ElementSetAttr("R55","vendor","unknown")
ElementSetAttr("R55","vendor_part_number","unknown")
ChangePinName("R55", 1, "1")
ChangePinName("R55", 2, "2")
ElementList(Need,"R6","0805","1K")
ElementSetAttr("R6","device","RESISTOR")
ElementSetAttr("R6","manufacturer","unknown")
ElementSetAttr("R6","manufacturer_part_number","unknown")
ElementSetAttr("R6","vendor","unknown")
ElementSetAttr("R6","vendor_part_number","unknown")
ChangePinName("R6", 1, "1")
ChangePinName("R6", 2, "2")
ElementList(Need,"R53","0805","1K")
ElementSetAttr("R53","device","RESISTOR")
ElementSetAttr("R53","manufacturer","unknown")
ElementSetAttr("R53","manufacturer_part_number","unknown")
ElementSetAttr("R53","vendor","unknown")
ElementSetAttr("R53","vendor_part_number","unknown")
ChangePinName("R53", 1, "1")
ChangePinName("R53", 2, "2")
ElementList(Need,"R54","0805","1K")
ElementSetAttr("R54","device","RESISTOR")
ElementSetAttr("R54","manufacturer","unknown")
ElementSetAttr("R54","manufacturer_part_number","unknown")
ElementSetAttr("R54","vendor","unknown")
ElementSetAttr("R54","vendor_part_number","unknown")
ChangePinName("R54", 1, "1")
ChangePinName("R54", 2, "2")
ElementList(Need,"R50","0805","1K")
ElementSetAttr("R50","device","RESISTOR")
ElementSetAttr("R50","manufacturer","unknown")
ElementSetAttr("R50","manufacturer_part_number","unknown")
ElementSetAttr("R50","vendor","unknown")
ElementSetAttr("R50","vendor_part_number","unknown")
ChangePinName("R50", 1, "1")
ChangePinName("R50", 2, "2")
ElementList(Need,"R49","0805","1K")
ElementSetAttr("R49","device","RESISTOR")
ElementSetAttr("R49","manufacturer","unknown")
ElementSetAttr("R49","manufacturer_part_number","unknown")
ElementSetAttr("R49","vendor","unknown")
ElementSetAttr("R49","vendor_part_number","unknown")
ChangePinName("R49", 1, "1")
ChangePinName("R49", 2, "2")
ElementList(Need,"R48","0805","1K")
ElementSetAttr("R48","device","RESISTOR")
ElementSetAttr("R48","manufacturer","unknown")
ElementSetAttr("R48","manufacturer_part_number","unknown")
ElementSetAttr("R48","vendor","unknown")
ElementSetAttr("R48","vendor_part_number","unknown")
ChangePinName("R48", 1, "1")
ChangePinName("R48", 2, "2")
ElementList(Need,"R47","0805","1K")
ElementSetAttr("R47","device","RESISTOR")
ElementSetAttr("R47","manufacturer","unknown")
ElementSetAttr("R47","manufacturer_part_number","unknown")
ElementSetAttr("R47","vendor","unknown")
ElementSetAttr("R47","vendor_part_number","unknown")
ChangePinName("R47", 1, "1")
ChangePinName("R47", 2, "2")
ElementList(Need,"R46","0805","1K")
ElementSetAttr("R46","device","RESISTOR")
ElementSetAttr("R46","manufacturer","unknown")
ElementSetAttr("R46","manufacturer_part_number","unknown")
ElementSetAttr("R46","vendor","unknown")
ElementSetAttr("R46","vendor_part_number","unknown")
ChangePinName("R46", 1, "1")
ChangePinName("R46", 2, "2")
ElementList(Need,"R45","0805","1K")
ElementSetAttr("R45","device","RESISTOR")
ElementSetAttr("R45","manufacturer","unknown")
ElementSetAttr("R45","manufacturer_part_number","unknown")
ElementSetAttr("R45","vendor","unknown")
ElementSetAttr("R45","vendor_part_number","unknown")
ChangePinName("R45", 1, "1")
ChangePinName("R45", 2, "2")
ElementList(Need,"R44","0805","1K")
ElementSetAttr("R44","device","RESISTOR")
ElementSetAttr("R44","manufacturer","unknown")
ElementSetAttr("R44","manufacturer_part_number","unknown")
ElementSetAttr("R44","vendor","unknown")
ElementSetAttr("R44","vendor_part_number","unknown")
ChangePinName("R44", 1, "1")
ChangePinName("R44", 2, "2")
ElementList(Need,"R5","0805","1K")
ElementSetAttr("R5","device","RESISTOR")
ElementSetAttr("R5","manufacturer","unknown")
ElementSetAttr("R5","manufacturer_part_number","unknown")
ElementSetAttr("R5","vendor","unknown")
ElementSetAttr("R5","vendor_part_number","unknown")
ChangePinName("R5", 1, "1")
ChangePinName("R5", 2, "2")
ElementList(Need,"R43","0805","1K")
ElementSetAttr("R43","device","RESISTOR")
ElementSetAttr("R43","manufacturer","unknown")
ElementSetAttr("R43","manufacturer_part_number","unknown")
ElementSetAttr("R43","vendor","unknown")
ElementSetAttr("R43","vendor_part_number","unknown")
ChangePinName("R43", 1, "1")
ChangePinName("R43", 2, "2")
ElementList(Need,"R42","0805","1K")
ElementSetAttr("R42","device","RESISTOR")
ElementSetAttr("R42","manufacturer","unknown")
ElementSetAttr("R42","manufacturer_part_number","unknown")
ElementSetAttr("R42","vendor","unknown")
ElementSetAttr("R42","vendor_part_number","unknown")
ChangePinName("R42", 1, "1")
ChangePinName("R42", 2, "2")
ElementList(Need,"R39","0805","1K")
ElementSetAttr("R39","device","RESISTOR")
ElementSetAttr("R39","manufacturer","unknown")
ElementSetAttr("R39","manufacturer_part_number","unknown")
ElementSetAttr("R39","vendor","unknown")
ElementSetAttr("R39","vendor_part_number","unknown")
ChangePinName("R39", 1, "1")
ChangePinName("R39", 2, "2")
ElementList(Need,"R41","0805","1K")
ElementSetAttr("R41","device","RESISTOR")
ElementSetAttr("R41","manufacturer","unknown")
ElementSetAttr("R41","manufacturer_part_number","unknown")
ElementSetAttr("R41","vendor","unknown")
ElementSetAttr("R41","vendor_part_number","unknown")
ChangePinName("R41", 1, "1")
ChangePinName("R41", 2, "2")
ElementList(Need,"R40","0805","1K")
ElementSetAttr("R40","device","RESISTOR")
ElementSetAttr("R40","manufacturer","unknown")
ElementSetAttr("R40","manufacturer_part_number","unknown")
ElementSetAttr("R40","vendor","unknown")
ElementSetAttr("R40","vendor_part_number","unknown")
ChangePinName("R40", 1, "1")
ChangePinName("R40", 2, "2")
ElementList(Need,"R26","0805","1K")
ElementSetAttr("R26","device","RESISTOR")
ElementSetAttr("R26","manufacturer","unknown")
ElementSetAttr("R26","manufacturer_part_number","unknown")
ElementSetAttr("R26","vendor","unknown")
ElementSetAttr("R26","vendor_part_number","unknown")
ChangePinName("R26", 1, "1")
ChangePinName("R26", 2, "2")
ElementList(Need,"R27","0805","1K")
ElementSetAttr("R27","device","RESISTOR")
ElementSetAttr("R27","manufacturer","unknown")
ElementSetAttr("R27","manufacturer_part_number","unknown")
ElementSetAttr("R27","vendor","unknown")
ElementSetAttr("R27","vendor_part_number","unknown")
ChangePinName("R27", 1, "1")
ChangePinName("R27", 2, "2")
ElementList(Need,"R25","0805","1K")
ElementSetAttr("R25","device","RESISTOR")
ElementSetAttr("R25","manufacturer","unknown")
ElementSetAttr("R25","manufacturer_part_number","unknown")
ElementSetAttr("R25","vendor","unknown")
ElementSetAttr("R25","vendor_part_number","unknown")
ChangePinName("R25", 1, "1")
ChangePinName("R25", 2, "2")
ElementList(Need,"R34","0805","1K")
ElementSetAttr("R34","device","RESISTOR")
ElementSetAttr("R34","manufacturer","unknown")
ElementSetAttr("R34","manufacturer_part_number","unknown")
ElementSetAttr("R34","vendor","unknown")
ElementSetAttr("R34","vendor_part_number","unknown")
ChangePinName("R34", 1, "1")
ChangePinName("R34", 2, "2")
ElementList(Need,"R35","0805","1K")
ElementSetAttr("R35","device","RESISTOR")
ElementSetAttr("R35","manufacturer","unknown")
ElementSetAttr("R35","manufacturer_part_number","unknown")
ElementSetAttr("R35","vendor","unknown")
ElementSetAttr("R35","vendor_part_number","unknown")
ChangePinName("R35", 1, "1")
ChangePinName("R35", 2, "2")
ElementList(Need,"R36","0805","1K")
ElementSetAttr("R36","device","RESISTOR")
ElementSetAttr("R36","manufacturer","unknown")
ElementSetAttr("R36","manufacturer_part_number","unknown")
ElementSetAttr("R36","vendor","unknown")
ElementSetAttr("R36","vendor_part_number","unknown")
ChangePinName("R36", 1, "1")
ChangePinName("R36", 2, "2")
ElementList(Need,"R38","0805","1K")
ElementSetAttr("R38","device","RESISTOR")
ElementSetAttr("R38","manufacturer","unknown")
ElementSetAttr("R38","manufacturer_part_number","unknown")
ElementSetAttr("R38","vendor","unknown")
ElementSetAttr("R38","vendor_part_number","unknown")
ChangePinName("R38", 1, "1")
ChangePinName("R38", 2, "2")
ElementList(Need,"R37","0805","1K")
ElementSetAttr("R37","device","RESISTOR")
ElementSetAttr("R37","manufacturer","unknown")
ElementSetAttr("R37","manufacturer_part_number","unknown")
ElementSetAttr("R37","vendor","unknown")
ElementSetAttr("R37","vendor_part_number","unknown")
ChangePinName("R37", 1, "1")
ChangePinName("R37", 2, "2")
ElementList(Need,"R33","0805","1K")
ElementSetAttr("R33","device","RESISTOR")
ElementSetAttr("R33","manufacturer","unknown")
ElementSetAttr("R33","manufacturer_part_number","unknown")
ElementSetAttr("R33","vendor","unknown")
ElementSetAttr("R33","vendor_part_number","unknown")
ChangePinName("R33", 1, "1")
ChangePinName("R33", 2, "2")
ElementList(Need,"R32","0805","1K")
ElementSetAttr("R32","device","RESISTOR")
ElementSetAttr("R32","manufacturer","unknown")
ElementSetAttr("R32","manufacturer_part_number","unknown")
ElementSetAttr("R32","vendor","unknown")
ElementSetAttr("R32","vendor_part_number","unknown")
ChangePinName("R32", 1, "1")
ChangePinName("R32", 2, "2")
ElementList(Need,"R31","0805","1K")
ElementSetAttr("R31","device","RESISTOR")
ElementSetAttr("R31","manufacturer","unknown")
ElementSetAttr("R31","manufacturer_part_number","unknown")
ElementSetAttr("R31","vendor","unknown")
ElementSetAttr("R31","vendor_part_number","unknown")
ChangePinName("R31", 1, "1")
ChangePinName("R31", 2, "2")
ElementList(Need,"R30","0805","1K")
ElementSetAttr("R30","device","RESISTOR")
ElementSetAttr("R30","manufacturer","unknown")
ElementSetAttr("R30","manufacturer_part_number","unknown")
ElementSetAttr("R30","vendor","unknown")
ElementSetAttr("R30","vendor_part_number","unknown")
ChangePinName("R30", 1, "1")
ChangePinName("R30", 2, "2")
ElementList(Need,"R29","0805","1K")
ElementSetAttr("R29","device","RESISTOR")
ElementSetAttr("R29","manufacturer","unknown")
ElementSetAttr("R29","manufacturer_part_number","unknown")
ElementSetAttr("R29","vendor","unknown")
ElementSetAttr("R29","vendor_part_number","unknown")
ChangePinName("R29", 1, "1")
ChangePinName("R29", 2, "2")
ElementList(Need,"R4","0805","1K")
ElementSetAttr("R4","device","RESISTOR")
ElementSetAttr("R4","manufacturer","unknown")
ElementSetAttr("R4","manufacturer_part_number","unknown")
ElementSetAttr("R4","vendor","unknown")
ElementSetAttr("R4","vendor_part_number","unknown")
ChangePinName("R4", 1, "1")
ChangePinName("R4", 2, "2")
ElementList(Need,"R28","0805","1K")
ElementSetAttr("R28","device","RESISTOR")
ElementSetAttr("R28","manufacturer","unknown")
ElementSetAttr("R28","manufacturer_part_number","unknown")
ElementSetAttr("R28","vendor","unknown")
ElementSetAttr("R28","vendor_part_number","unknown")
ChangePinName("R28", 1, "1")
ChangePinName("R28", 2, "2")
ElementList(Need,"R24","0805","1K")
ElementSetAttr("R24","device","RESISTOR")
ElementSetAttr("R24","manufacturer","unknown")
ElementSetAttr("R24","manufacturer_part_number","unknown")
ElementSetAttr("R24","vendor","unknown")
ElementSetAttr("R24","vendor_part_number","unknown")
ChangePinName("R24", 1, "1")
ChangePinName("R24", 2, "2")
ElementList(Need,"R23","0805","1K")
ElementSetAttr("R23","device","RESISTOR")
ElementSetAttr("R23","manufacturer","unknown")
ElementSetAttr("R23","manufacturer_part_number","unknown")
ElementSetAttr("R23","vendor","unknown")
ElementSetAttr("R23","vendor_part_number","unknown")
ChangePinName("R23", 1, "1")
ChangePinName("R23", 2, "2")
ElementList(Need,"R22","0805","1K")
ElementSetAttr("R22","device","RESISTOR")
ElementSetAttr("R22","manufacturer","unknown")
ElementSetAttr("R22","manufacturer_part_number","unknown")
ElementSetAttr("R22","vendor","unknown")
ElementSetAttr("R22","vendor_part_number","unknown")
ChangePinName("R22", 1, "1")
ChangePinName("R22", 2, "2")
ElementList(Need,"R20","0805","1K")
ElementSetAttr("R20","device","RESISTOR")
ElementSetAttr("R20","manufacturer","unknown")
ElementSetAttr("R20","manufacturer_part_number","unknown")
ElementSetAttr("R20","vendor","unknown")
ElementSetAttr("R20","vendor_part_number","unknown")
ChangePinName("R20", 1, "1")
ChangePinName("R20", 2, "2")
ElementList(Need,"R3","0805","1K")
ElementSetAttr("R3","device","RESISTOR")
ElementSetAttr("R3","manufacturer","unknown")
ElementSetAttr("R3","manufacturer_part_number","unknown")
ElementSetAttr("R3","vendor","unknown")
ElementSetAttr("R3","vendor_part_number","unknown")
ChangePinName("R3", 1, "1")
ChangePinName("R3", 2, "2")
ElementList(Need,"R21","0805","1K")
ElementSetAttr("R21","device","RESISTOR")
ElementSetAttr("R21","manufacturer","unknown")
ElementSetAttr("R21","manufacturer_part_number","unknown")
ElementSetAttr("R21","vendor","unknown")
ElementSetAttr("R21","vendor_part_number","unknown")
ChangePinName("R21", 1, "1")
ChangePinName("R21", 2, "2")
ElementList(Need,"R19","0805","1K")
ElementSetAttr("R19","device","RESISTOR")
ElementSetAttr("R19","manufacturer","unknown")
ElementSetAttr("R19","manufacturer_part_number","unknown")
ElementSetAttr("R19","vendor","unknown")
ElementSetAttr("R19","vendor_part_number","unknown")
ChangePinName("R19", 1, "1")
ChangePinName("R19", 2, "2")
ElementList(Need,"R18","0805","1K")
ElementSetAttr("R18","device","RESISTOR")
ElementSetAttr("R18","manufacturer","unknown")
ElementSetAttr("R18","manufacturer_part_number","unknown")
ElementSetAttr("R18","vendor","unknown")
ElementSetAttr("R18","vendor_part_number","unknown")
ChangePinName("R18", 1, "1")
ChangePinName("R18", 2, "2")
ElementList(Need,"R17","0805","1K")
ElementSetAttr("R17","device","RESISTOR")
ElementSetAttr("R17","manufacturer","unknown")
ElementSetAttr("R17","manufacturer_part_number","unknown")
ElementSetAttr("R17","vendor","unknown")
ElementSetAttr("R17","vendor_part_number","unknown")
ChangePinName("R17", 1, "1")
ChangePinName("R17", 2, "2")
ElementList(Need,"R16","0805","1K")
ElementSetAttr("R16","device","RESISTOR")
ElementSetAttr("R16","manufacturer","unknown")
ElementSetAttr("R16","manufacturer_part_number","unknown")
ElementSetAttr("R16","vendor","unknown")
ElementSetAttr("R16","vendor_part_number","unknown")
ChangePinName("R16", 1, "1")
ChangePinName("R16", 2, "2")
ElementList(Need,"R15","0805","1K")
ElementSetAttr("R15","device","RESISTOR")
ElementSetAttr("R15","manufacturer","unknown")
ElementSetAttr("R15","manufacturer_part_number","unknown")
ElementSetAttr("R15","vendor","unknown")
ElementSetAttr("R15","vendor_part_number","unknown")
ChangePinName("R15", 1, "1")
ChangePinName("R15", 2, "2")
ElementList(Need,"R14","0805","1K")
ElementSetAttr("R14","device","RESISTOR")
ElementSetAttr("R14","manufacturer","unknown")
ElementSetAttr("R14","manufacturer_part_number","unknown")
ElementSetAttr("R14","vendor","unknown")
ElementSetAttr("R14","vendor_part_number","unknown")
ChangePinName("R14", 1, "1")
ChangePinName("R14", 2, "2")
ElementList(Need,"R76","0805","1K")
ElementSetAttr("R76","device","RESISTOR")
ElementSetAttr("R76","manufacturer","unknown")
ElementSetAttr("R76","manufacturer_part_number","unknown")
ElementSetAttr("R76","vendor","unknown")
ElementSetAttr("R76","vendor_part_number","unknown")
ChangePinName("R76", 1, "1")
ChangePinName("R76", 2, "2")
ElementList(Need,"LED40","T1.75_LED.fp","unknown")
ElementSetAttr("LED40","device","LED")
ElementSetAttr("LED40","manufacturer","unknown")
ElementSetAttr("LED40","manufacturer_part_number","unknown")
ElementSetAttr("LED40","vendor","unknown")
ElementSetAttr("LED40","vendor_part_number","unknown")
ChangePinName("LED40", 2, "K")
ChangePinName("LED40", 1, "A")
ElementList(Need,"LED43","T1.75_LED.fp","unknown")
ElementSetAttr("LED43","device","LED")
ElementSetAttr("LED43","manufacturer","unknown")
ElementSetAttr("LED43","manufacturer_part_number","unknown")
ElementSetAttr("LED43","vendor","unknown")
ElementSetAttr("LED43","vendor_part_number","unknown")
ChangePinName("LED43", 2, "K")
ChangePinName("LED43", 1, "A")
ElementList(Need,"LED46","T1.75_LED.fp","unknown")
ElementSetAttr("LED46","device","LED")
ElementSetAttr("LED46","manufacturer","unknown")
ElementSetAttr("LED46","manufacturer_part_number","unknown")
ElementSetAttr("LED46","vendor","unknown")
ElementSetAttr("LED46","vendor_part_number","unknown")
ChangePinName("LED46", 2, "K")
ChangePinName("LED46", 1, "A")
ElementList(Need,"LED45","T1.75_LED.fp","unknown")
ElementSetAttr("LED45","device","LED")
ElementSetAttr("LED45","manufacturer","unknown")
ElementSetAttr("LED45","manufacturer_part_number","unknown")
ElementSetAttr("LED45","vendor","unknown")
ElementSetAttr("LED45","vendor_part_number","unknown")
ChangePinName("LED45", 2, "K")
ChangePinName("LED45", 1, "A")
ElementList(Need,"LED48","T1.75_LED.fp","unknown")
ElementSetAttr("LED48","device","LED")
ElementSetAttr("LED48","manufacturer","unknown")
ElementSetAttr("LED48","manufacturer_part_number","unknown")
ElementSetAttr("LED48","vendor","unknown")
ElementSetAttr("LED48","vendor_part_number","unknown")
ChangePinName("LED48", 2, "K")
ChangePinName("LED48", 1, "A")
ElementList(Need,"LED50","T1.75_LED.fp","unknown")
ElementSetAttr("LED50","device","LED")
ElementSetAttr("LED50","manufacturer","unknown")
ElementSetAttr("LED50","manufacturer_part_number","unknown")
ElementSetAttr("LED50","vendor","unknown")
ElementSetAttr("LED50","vendor_part_number","unknown")
ChangePinName("LED50", 2, "K")
ChangePinName("LED50", 1, "A")
ElementList(Need,"LED49","T1.75_LED.fp","unknown")
ElementSetAttr("LED49","device","LED")
ElementSetAttr("LED49","manufacturer","unknown")
ElementSetAttr("LED49","manufacturer_part_number","unknown")
ElementSetAttr("LED49","vendor","unknown")
ElementSetAttr("LED49","vendor_part_number","unknown")
ChangePinName("LED49", 2, "K")
ChangePinName("LED49", 1, "A")
ElementList(Need,"LED51","T1.75_LED.fp","unknown")
ElementSetAttr("LED51","device","LED")
ElementSetAttr("LED51","manufacturer","unknown")
ElementSetAttr("LED51","manufacturer_part_number","unknown")
ElementSetAttr("LED51","vendor","unknown")
ElementSetAttr("LED51","vendor_part_number","unknown")
ChangePinName("LED51", 2, "K")
ChangePinName("LED51", 1, "A")
ElementList(Need,"LED52","T1.75_LED.fp","unknown")
ElementSetAttr("LED52","device","LED")
ElementSetAttr("LED52","manufacturer","unknown")
ElementSetAttr("LED52","manufacturer_part_number","unknown")
ElementSetAttr("LED52","vendor","unknown")
ElementSetAttr("LED52","vendor_part_number","unknown")
ChangePinName("LED52", 2, "K")
ChangePinName("LED52", 1, "A")
ElementList(Need,"LED54","T1.75_LED.fp","unknown")
ElementSetAttr("LED54","device","LED")
ElementSetAttr("LED54","manufacturer","unknown")
ElementSetAttr("LED54","manufacturer_part_number","unknown")
ElementSetAttr("LED54","vendor","unknown")
ElementSetAttr("LED54","vendor_part_number","unknown")
ChangePinName("LED54", 2, "K")
ChangePinName("LED54", 1, "A")
ElementList(Need,"LED25","T1.75_LED.fp","unknown")
ElementSetAttr("LED25","device","LED")
ElementSetAttr("LED25","manufacturer","unknown")
ElementSetAttr("LED25","manufacturer_part_number","unknown")
ElementSetAttr("LED25","vendor","unknown")
ElementSetAttr("LED25","vendor_part_number","unknown")
ChangePinName("LED25", 2, "K")
ChangePinName("LED25", 1, "A")
ElementList(Need,"LED68","T1.75_LED.fp","unknown")
ElementSetAttr("LED68","device","LED")
ElementSetAttr("LED68","manufacturer","unknown")
ElementSetAttr("LED68","manufacturer_part_number","unknown")
ElementSetAttr("LED68","vendor","unknown")
ElementSetAttr("LED68","vendor_part_number","unknown")
ChangePinName("LED68", 2, "K")
ChangePinName("LED68", 1, "A")
ElementList(Need,"LED28","T1.75_LED.fp","unknown")
ElementSetAttr("LED28","device","LED")
ElementSetAttr("LED28","manufacturer","unknown")
ElementSetAttr("LED28","manufacturer_part_number","unknown")
ElementSetAttr("LED28","vendor","unknown")
ElementSetAttr("LED28","vendor_part_number","unknown")
ChangePinName("LED28", 2, "K")
ChangePinName("LED28", 1, "A")
ElementList(Need,"LED27","T1.75_LED.fp","unknown")
ElementSetAttr("LED27","device","LED")
ElementSetAttr("LED27","manufacturer","unknown")
ElementSetAttr("LED27","manufacturer_part_number","unknown")
ElementSetAttr("LED27","vendor","unknown")
ElementSetAttr("LED27","vendor_part_number","unknown")
ChangePinName("LED27", 2, "K")
ChangePinName("LED27", 1, "A")
ElementList(Need,"LED26","T1.75_LED.fp","unknown")
ElementSetAttr("LED26","device","LED")
ElementSetAttr("LED26","manufacturer","unknown")
ElementSetAttr("LED26","manufacturer_part_number","unknown")
ElementSetAttr("LED26","vendor","unknown")
ElementSetAttr("LED26","vendor_part_number","unknown")
ChangePinName("LED26", 2, "K")
ChangePinName("LED26", 1, "A")
ElementList(Need,"LED24","T1.75_LED.fp","unknown")
ElementSetAttr("LED24","device","LED")
ElementSetAttr("LED24","manufacturer","unknown")
ElementSetAttr("LED24","manufacturer_part_number","unknown")
ElementSetAttr("LED24","vendor","unknown")
ElementSetAttr("LED24","vendor_part_number","unknown")
ChangePinName("LED24", 2, "K")
ChangePinName("LED24", 1, "A")
ElementList(Need,"LED23","T1.75_LED.fp","unknown")
ElementSetAttr("LED23","device","LED")
ElementSetAttr("LED23","manufacturer","unknown")
ElementSetAttr("LED23","manufacturer_part_number","unknown")
ElementSetAttr("LED23","vendor","unknown")
ElementSetAttr("LED23","vendor_part_number","unknown")
ChangePinName("LED23", 2, "K")
ChangePinName("LED23", 1, "A")
ElementList(Need,"LED22","T1.75_LED.fp","unknown")
ElementSetAttr("LED22","device","LED")
ElementSetAttr("LED22","manufacturer","unknown")
ElementSetAttr("LED22","manufacturer_part_number","unknown")
ElementSetAttr("LED22","vendor","unknown")
ElementSetAttr("LED22","vendor_part_number","unknown")
ChangePinName("LED22", 2, "K")
ChangePinName("LED22", 1, "A")
ElementList(Need,"LED21","T1.75_LED.fp","unknown")
ElementSetAttr("LED21","device","LED")
ElementSetAttr("LED21","manufacturer","unknown")
ElementSetAttr("LED21","manufacturer_part_number","unknown")
ElementSetAttr("LED21","vendor","unknown")
ElementSetAttr("LED21","vendor_part_number","unknown")
ChangePinName("LED21", 2, "K")
ChangePinName("LED21", 1, "A")
ElementList(Need,"R13","0805","1K")
ElementSetAttr("R13","device","RESISTOR")
ElementSetAttr("R13","manufacturer","unknown")
ElementSetAttr("R13","manufacturer_part_number","unknown")
ElementSetAttr("R13","vendor","unknown")
ElementSetAttr("R13","vendor_part_number","unknown")
ChangePinName("R13", 1, "1")
ChangePinName("R13", 2, "2")
ElementList(Need,"LED74","T1.75_LED.fp","unknown")
ElementSetAttr("LED74","device","LED")
ElementSetAttr("LED74","manufacturer","unknown")
ElementSetAttr("LED74","manufacturer_part_number","unknown")
ElementSetAttr("LED74","vendor","unknown")
ElementSetAttr("LED74","vendor_part_number","unknown")
ChangePinName("LED74", 2, "K")
ChangePinName("LED74", 1, "A")
ElementList(Need,"LED72","T1.75_LED.fp","unknown")
ElementSetAttr("LED72","device","LED")
ElementSetAttr("LED72","manufacturer","unknown")
ElementSetAttr("LED72","manufacturer_part_number","unknown")
ElementSetAttr("LED72","vendor","unknown")
ElementSetAttr("LED72","vendor_part_number","unknown")
ChangePinName("LED72", 2, "K")
ChangePinName("LED72", 1, "A")
ElementList(Need,"LED70","T1.75_LED.fp","unknown")
ElementSetAttr("LED70","device","LED")
ElementSetAttr("LED70","manufacturer","unknown")
ElementSetAttr("LED70","manufacturer_part_number","unknown")
ElementSetAttr("LED70","vendor","unknown")
ElementSetAttr("LED70","vendor_part_number","unknown")
ChangePinName("LED70", 2, "K")
ChangePinName("LED70", 1, "A")
ElementList(Need,"LED66","T1.75_LED.fp","unknown")
ElementSetAttr("LED66","device","LED")
ElementSetAttr("LED66","manufacturer","unknown")
ElementSetAttr("LED66","manufacturer_part_number","unknown")
ElementSetAttr("LED66","vendor","unknown")
ElementSetAttr("LED66","vendor_part_number","unknown")
ChangePinName("LED66", 2, "K")
ChangePinName("LED66", 1, "A")
ElementList(Need,"LED64","T1.75_LED.fp","unknown")
ElementSetAttr("LED64","device","LED")
ElementSetAttr("LED64","manufacturer","unknown")
ElementSetAttr("LED64","manufacturer_part_number","unknown")
ElementSetAttr("LED64","vendor","unknown")
ElementSetAttr("LED64","vendor_part_number","unknown")
ChangePinName("LED64", 2, "K")
ChangePinName("LED64", 1, "A")
ElementList(Need,"LED78","T1.75_LED.fp","unknown")
ElementSetAttr("LED78","device","LED")
ElementSetAttr("LED78","manufacturer","unknown")
ElementSetAttr("LED78","manufacturer_part_number","unknown")
ElementSetAttr("LED78","vendor","unknown")
ElementSetAttr("LED78","vendor_part_number","unknown")
ChangePinName("LED78", 2, "K")
ChangePinName("LED78", 1, "A")
ElementList(Need,"LED76","T1.75_LED.fp","unknown")
ElementSetAttr("LED76","device","LED")
ElementSetAttr("LED76","manufacturer","unknown")
ElementSetAttr("LED76","manufacturer_part_number","unknown")
ElementSetAttr("LED76","vendor","unknown")
ElementSetAttr("LED76","vendor_part_number","unknown")
ChangePinName("LED76", 2, "K")
ChangePinName("LED76", 1, "A")
ElementList(Need,"LED86","T1.75_LED.fp","unknown")
ElementSetAttr("LED86","device","LED")
ElementSetAttr("LED86","manufacturer","unknown")
ElementSetAttr("LED86","manufacturer_part_number","unknown")
ElementSetAttr("LED86","vendor","unknown")
ElementSetAttr("LED86","vendor_part_number","unknown")
ChangePinName("LED86", 2, "K")
ChangePinName("LED86", 1, "A")
ElementList(Need,"LED84","T1.75_LED.fp","unknown")
ElementSetAttr("LED84","device","LED")
ElementSetAttr("LED84","manufacturer","unknown")
ElementSetAttr("LED84","manufacturer_part_number","unknown")
ElementSetAttr("LED84","vendor","unknown")
ElementSetAttr("LED84","vendor_part_number","unknown")
ChangePinName("LED84", 2, "K")
ChangePinName("LED84", 1, "A")
ElementList(Need,"LED82","T1.75_LED.fp","unknown")
ElementSetAttr("LED82","device","LED")
ElementSetAttr("LED82","manufacturer","unknown")
ElementSetAttr("LED82","manufacturer_part_number","unknown")
ElementSetAttr("LED82","vendor","unknown")
ElementSetAttr("LED82","vendor_part_number","unknown")
ChangePinName("LED82", 2, "K")
ChangePinName("LED82", 1, "A")
ElementList(Need,"LED80","T1.75_LED.fp","unknown")
ElementSetAttr("LED80","device","LED")
ElementSetAttr("LED80","manufacturer","unknown")
ElementSetAttr("LED80","manufacturer_part_number","unknown")
ElementSetAttr("LED80","vendor","unknown")
ElementSetAttr("LED80","vendor_part_number","unknown")
ChangePinName("LED80", 2, "K")
ChangePinName("LED80", 1, "A")
ElementList(Need,"LED2","T1.75_LED.fp","unknown")
ElementSetAttr("LED2","device","LED")
ElementSetAttr("LED2","manufacturer","unknown")
ElementSetAttr("LED2","manufacturer_part_number","unknown")
ElementSetAttr("LED2","vendor","unknown")
ElementSetAttr("LED2","vendor_part_number","unknown")
ChangePinName("LED2", 2, "K")
ChangePinName("LED2", 1, "A")
ElementList(Need,"LED4","T1.75_LED.fp","unknown")
ElementSetAttr("LED4","device","LED")
ElementSetAttr("LED4","manufacturer","unknown")
ElementSetAttr("LED4","manufacturer_part_number","unknown")
ElementSetAttr("LED4","vendor","unknown")
ElementSetAttr("LED4","vendor_part_number","unknown")
ChangePinName("LED4", 2, "K")
ChangePinName("LED4", 1, "A")
ElementList(Need,"LED8","T1.75_LED.fp","unknown")
ElementSetAttr("LED8","device","LED")
ElementSetAttr("LED8","manufacturer","unknown")
ElementSetAttr("LED8","manufacturer_part_number","unknown")
ElementSetAttr("LED8","vendor","unknown")
ElementSetAttr("LED8","vendor_part_number","unknown")
ChangePinName("LED8", 2, "K")
ChangePinName("LED8", 1, "A")
ElementList(Need,"LED6","T1.75_LED.fp","unknown")
ElementSetAttr("LED6","device","LED")
ElementSetAttr("LED6","manufacturer","unknown")
ElementSetAttr("LED6","manufacturer_part_number","unknown")
ElementSetAttr("LED6","vendor","unknown")
ElementSetAttr("LED6","vendor_part_number","unknown")
ChangePinName("LED6", 2, "K")
ChangePinName("LED6", 1, "A")
ElementList(Need,"LED10","T1.75_LED.fp","unknown")
ElementSetAttr("LED10","device","LED")
ElementSetAttr("LED10","manufacturer","unknown")
ElementSetAttr("LED10","manufacturer_part_number","unknown")
ElementSetAttr("LED10","vendor","unknown")
ElementSetAttr("LED10","vendor_part_number","unknown")
ChangePinName("LED10", 2, "K")
ChangePinName("LED10", 1, "A")
ElementList(Need,"LED12","T1.75_LED.fp","unknown")
ElementSetAttr("LED12","device","LED")
ElementSetAttr("LED12","manufacturer","unknown")
ElementSetAttr("LED12","manufacturer_part_number","unknown")
ElementSetAttr("LED12","vendor","unknown")
ElementSetAttr("LED12","vendor_part_number","unknown")
ChangePinName("LED12", 2, "K")
ChangePinName("LED12", 1, "A")
ElementList(Need,"LED14","T1.75_LED.fp","unknown")
ElementSetAttr("LED14","device","LED")
ElementSetAttr("LED14","manufacturer","unknown")
ElementSetAttr("LED14","manufacturer_part_number","unknown")
ElementSetAttr("LED14","vendor","unknown")
ElementSetAttr("LED14","vendor_part_number","unknown")
ChangePinName("LED14", 2, "K")
ChangePinName("LED14", 1, "A")
ElementList(Need,"LED5","T1.75_LED.fp","unknown")
ElementSetAttr("LED5","device","LED")
ElementSetAttr("LED5","manufacturer","unknown")
ElementSetAttr("LED5","manufacturer_part_number","unknown")
ElementSetAttr("LED5","vendor","unknown")
ElementSetAttr("LED5","vendor_part_number","unknown")
ChangePinName("LED5", 2, "K")
ChangePinName("LED5", 1, "A")
ElementList(Need,"LED1","T1.75_LED.fp","unknown")
ElementSetAttr("LED1","device","LED")
ElementSetAttr("LED1","manufacturer","unknown")
ElementSetAttr("LED1","manufacturer_part_number","unknown")
ElementSetAttr("LED1","vendor","unknown")
ElementSetAttr("LED1","vendor_part_number","unknown")
ChangePinName("LED1", 2, "K")
ChangePinName("LED1", 1, "A")
ElementList(Need,"LED3","T1.75_LED.fp","unknown")
ElementSetAttr("LED3","device","LED")
ElementSetAttr("LED3","manufacturer","unknown")
ElementSetAttr("LED3","manufacturer_part_number","unknown")
ElementSetAttr("LED3","vendor","unknown")
ElementSetAttr("LED3","vendor_part_number","unknown")
ChangePinName("LED3", 2, "K")
ChangePinName("LED3", 1, "A")
ElementList(Need,"LED7","T1.75_LED.fp","unknown")
ElementSetAttr("LED7","device","LED")
ElementSetAttr("LED7","manufacturer","unknown")
ElementSetAttr("LED7","manufacturer_part_number","unknown")
ElementSetAttr("LED7","vendor","unknown")
ElementSetAttr("LED7","vendor_part_number","unknown")
ChangePinName("LED7", 2, "K")
ChangePinName("LED7", 1, "A")
ElementList(Need,"LED9","T1.75_LED.fp","unknown")
ElementSetAttr("LED9","device","LED")
ElementSetAttr("LED9","manufacturer","unknown")
ElementSetAttr("LED9","manufacturer_part_number","unknown")
ElementSetAttr("LED9","vendor","unknown")
ElementSetAttr("LED9","vendor_part_number","unknown")
ChangePinName("LED9", 2, "K")
ChangePinName("LED9", 1, "A")
ElementList(Need,"LED11","T1.75_LED.fp","unknown")
ElementSetAttr("LED11","device","LED")
ElementSetAttr("LED11","manufacturer","unknown")
ElementSetAttr("LED11","manufacturer_part_number","unknown")
ElementSetAttr("LED11","vendor","unknown")
ElementSetAttr("LED11","vendor_part_number","unknown")
ChangePinName("LED11", 2, "K")
ChangePinName("LED11", 1, "A")
ElementList(Need,"LED13","T1.75_LED.fp","unknown")
ElementSetAttr("LED13","device","LED")
ElementSetAttr("LED13","manufacturer","unknown")
ElementSetAttr("LED13","manufacturer_part_number","unknown")
ElementSetAttr("LED13","vendor","unknown")
ElementSetAttr("LED13","vendor_part_number","unknown")
ChangePinName("LED13", 2, "K")
ChangePinName("LED13", 1, "A")
ElementList(Need,"LED77","T1.75_LED.fp","unknown")
ElementSetAttr("LED77","device","LED")
ElementSetAttr("LED77","manufacturer","unknown")
ElementSetAttr("LED77","manufacturer_part_number","unknown")
ElementSetAttr("LED77","vendor","unknown")
ElementSetAttr("LED77","vendor_part_number","unknown")
ChangePinName("LED77", 2, "K")
ChangePinName("LED77", 1, "A")
ElementList(Need,"LED75","T1.75_LED.fp","unknown")
ElementSetAttr("LED75","device","LED")
ElementSetAttr("LED75","manufacturer","unknown")
ElementSetAttr("LED75","manufacturer_part_number","unknown")
ElementSetAttr("LED75","vendor","unknown")
ElementSetAttr("LED75","vendor_part_number","unknown")
ChangePinName("LED75", 2, "K")
ChangePinName("LED75", 1, "A")
ElementList(Need,"LED73","T1.75_LED.fp","unknown")
ElementSetAttr("LED73","device","LED")
ElementSetAttr("LED73","manufacturer","unknown")
ElementSetAttr("LED73","manufacturer_part_number","unknown")
ElementSetAttr("LED73","vendor","unknown")
ElementSetAttr("LED73","vendor_part_number","unknown")
ChangePinName("LED73", 2, "K")
ChangePinName("LED73", 1, "A")
ElementList(Need,"LED71","T1.75_LED.fp","unknown")
ElementSetAttr("LED71","device","LED")
ElementSetAttr("LED71","manufacturer","unknown")
ElementSetAttr("LED71","manufacturer_part_number","unknown")
ElementSetAttr("LED71","vendor","unknown")
ElementSetAttr("LED71","vendor_part_number","unknown")
ChangePinName("LED71", 2, "K")
ChangePinName("LED71", 1, "A")
ElementList(Need,"LED69","T1.75_LED.fp","unknown")
ElementSetAttr("LED69","device","LED")
ElementSetAttr("LED69","manufacturer","unknown")
ElementSetAttr("LED69","manufacturer_part_number","unknown")
ElementSetAttr("LED69","vendor","unknown")
ElementSetAttr("LED69","vendor_part_number","unknown")
ChangePinName("LED69", 2, "K")
ChangePinName("LED69", 1, "A")
ElementList(Need,"LED67","T1.75_LED.fp","unknown")
ElementSetAttr("LED67","device","LED")
ElementSetAttr("LED67","manufacturer","unknown")
ElementSetAttr("LED67","manufacturer_part_number","unknown")
ElementSetAttr("LED67","vendor","unknown")
ElementSetAttr("LED67","vendor_part_number","unknown")
ChangePinName("LED67", 2, "K")
ChangePinName("LED67", 1, "A")
ElementList(Need,"LED65","T1.75_LED.fp","unknown")
ElementSetAttr("LED65","device","LED")
ElementSetAttr("LED65","manufacturer","unknown")
ElementSetAttr("LED65","manufacturer_part_number","unknown")
ElementSetAttr("LED65","vendor","unknown")
ElementSetAttr("LED65","vendor_part_number","unknown")
ChangePinName("LED65", 2, "K")
ChangePinName("LED65", 1, "A")
ElementList(Need,"LED63","T1.75_LED.fp","unknown")
ElementSetAttr("LED63","device","LED")
ElementSetAttr("LED63","manufacturer","unknown")
ElementSetAttr("LED63","manufacturer_part_number","unknown")
ElementSetAttr("LED63","vendor","unknown")
ElementSetAttr("LED63","vendor_part_number","unknown")
ChangePinName("LED63", 2, "K")
ChangePinName("LED63", 1, "A")
ElementList(Need,"LED85","T1.75_LED.fp","unknown")
ElementSetAttr("LED85","device","LED")
ElementSetAttr("LED85","manufacturer","unknown")
ElementSetAttr("LED85","manufacturer_part_number","unknown")
ElementSetAttr("LED85","vendor","unknown")
ElementSetAttr("LED85","vendor_part_number","unknown")
ChangePinName("LED85", 2, "K")
ChangePinName("LED85", 1, "A")
ElementList(Need,"LED83","T1.75_LED.fp","unknown")
ElementSetAttr("LED83","device","LED")
ElementSetAttr("LED83","manufacturer","unknown")
ElementSetAttr("LED83","manufacturer_part_number","unknown")
ElementSetAttr("LED83","vendor","unknown")
ElementSetAttr("LED83","vendor_part_number","unknown")
ChangePinName("LED83", 2, "K")
ChangePinName("LED83", 1, "A")
ElementList(Need,"LED81","T1.75_LED.fp","unknown")
ElementSetAttr("LED81","device","LED")
ElementSetAttr("LED81","manufacturer","unknown")
ElementSetAttr("LED81","manufacturer_part_number","unknown")
ElementSetAttr("LED81","vendor","unknown")
ElementSetAttr("LED81","vendor_part_number","unknown")
ChangePinName("LED81", 2, "K")
ChangePinName("LED81", 1, "A")
ElementList(Need,"LED79","T1.75_LED.fp","unknown")
ElementSetAttr("LED79","device","LED")
ElementSetAttr("LED79","manufacturer","unknown")
ElementSetAttr("LED79","manufacturer_part_number","unknown")
ElementSetAttr("LED79","vendor","unknown")
ElementSetAttr("LED79","vendor_part_number","unknown")
ChangePinName("LED79", 2, "K")
ChangePinName("LED79", 1, "A")
ElementList(Need,"R2","0805","1K")
ElementSetAttr("R2","device","RESISTOR")
ElementSetAttr("R2","manufacturer","unknown")
ElementSetAttr("R2","manufacturer_part_number","unknown")
ElementSetAttr("R2","vendor","unknown")
ElementSetAttr("R2","vendor_part_number","unknown")
ChangePinName("R2", 1, "1")
ChangePinName("R2", 2, "2")
ElementList(Need,"R1","0805","1K")
ElementSetAttr("R1","device","RESISTOR")
ElementSetAttr("R1","manufacturer","unknown")
ElementSetAttr("R1","manufacturer_part_number","unknown")
ElementSetAttr("R1","vendor","unknown")
ElementSetAttr("R1","vendor_part_number","unknown")
ChangePinName("R1", 1, "1")
ChangePinName("R1", 2, "2")
ElementList(Need,"R12","0805","1K")
ElementSetAttr("R12","device","RESISTOR")
ElementSetAttr("R12","manufacturer","unknown")
ElementSetAttr("R12","manufacturer_part_number","unknown")
ElementSetAttr("R12","vendor","unknown")
ElementSetAttr("R12","vendor_part_number","unknown")
ChangePinName("R12", 1, "1")
ChangePinName("R12", 2, "2")
ElementList(Need,"R11","0805","1K")
ElementSetAttr("R11","device","RESISTOR")
ElementSetAttr("R11","manufacturer","unknown")
ElementSetAttr("R11","manufacturer_part_number","unknown")
ElementSetAttr("R11","vendor","unknown")
ElementSetAttr("R11","vendor_part_number","unknown")
ChangePinName("R11", 1, "1")
ChangePinName("R11", 2, "2")
ElementList(Need,"R10","0805","1K")
ElementSetAttr("R10","device","RESISTOR")
ElementSetAttr("R10","manufacturer","unknown")
ElementSetAttr("R10","manufacturer_part_number","unknown")
ElementSetAttr("R10","vendor","unknown")
ElementSetAttr("R10","vendor_part_number","unknown")
ChangePinName("R10", 1, "1")
ChangePinName("R10", 2, "2")
ElementList(Need,"R9","0805","1K")
ElementSetAttr("R9","device","RESISTOR")
ElementSetAttr("R9","manufacturer","unknown")
ElementSetAttr("R9","manufacturer_part_number","unknown")
ElementSetAttr("R9","vendor","unknown")
ElementSetAttr("R9","vendor_part_number","unknown")
ChangePinName("R9", 1, "1")
ChangePinName("R9", 2, "2")
ElementList(Need,"R8","0805","1K")
ElementSetAttr("R8","device","RESISTOR")
ElementSetAttr("R8","manufacturer","unknown")
ElementSetAttr("R8","manufacturer_part_number","unknown")
ElementSetAttr("R8","vendor","unknown")
ElementSetAttr("R8","vendor_part_number","unknown")
ChangePinName("R8", 1, "1")
ChangePinName("R8", 2, "2")
ElementList(Need,"LED61","T1.75_LED.fp","unknown")
ElementSetAttr("LED61","device","LED")
ElementSetAttr("LED61","manufacturer","unknown")
ElementSetAttr("LED61","manufacturer_part_number","unknown")
ElementSetAttr("LED61","vendor","unknown")
ElementSetAttr("LED61","vendor_part_number","unknown")
ChangePinName("LED61", 2, "K")
ChangePinName("LED61", 1, "A")
ElementList(Need,"LED59","T1.75_LED.fp","unknown")
ElementSetAttr("LED59","device","LED")
ElementSetAttr("LED59","manufacturer","unknown")
ElementSetAttr("LED59","manufacturer_part_number","unknown")
ElementSetAttr("LED59","vendor","unknown")
ElementSetAttr("LED59","vendor_part_number","unknown")
ChangePinName("LED59", 2, "K")
ChangePinName("LED59", 1, "A")
ElementList(Need,"LED57","T1.75_LED.fp","unknown")
ElementSetAttr("LED57","device","LED")
ElementSetAttr("LED57","manufacturer","unknown")
ElementSetAttr("LED57","manufacturer_part_number","unknown")
ElementSetAttr("LED57","vendor","unknown")
ElementSetAttr("LED57","vendor_part_number","unknown")
ChangePinName("LED57", 2, "K")
ChangePinName("LED57", 1, "A")
ElementList(Need,"LED55","T1.75_LED.fp","unknown")
ElementSetAttr("LED55","device","LED")
ElementSetAttr("LED55","manufacturer","unknown")
ElementSetAttr("LED55","manufacturer_part_number","unknown")
ElementSetAttr("LED55","vendor","unknown")
ElementSetAttr("LED55","vendor_part_number","unknown")
ChangePinName("LED55", 2, "K")
ChangePinName("LED55", 1, "A")
ElementList(Need,"LED53","T1.75_LED.fp","unknown")
ElementSetAttr("LED53","device","LED")
ElementSetAttr("LED53","manufacturer","unknown")
ElementSetAttr("LED53","manufacturer_part_number","unknown")
ElementSetAttr("LED53","vendor","unknown")
ElementSetAttr("LED53","vendor_part_number","unknown")
ChangePinName("LED53", 2, "K")
ChangePinName("LED53", 1, "A")
ElementList(Need,"LED62","T1.75_LED.fp","unknown")
ElementSetAttr("LED62","device","LED")
ElementSetAttr("LED62","manufacturer","unknown")
ElementSetAttr("LED62","manufacturer_part_number","unknown")
ElementSetAttr("LED62","vendor","unknown")
ElementSetAttr("LED62","vendor_part_number","unknown")
ChangePinName("LED62", 2, "K")
ChangePinName("LED62", 1, "A")
ElementList(Need,"LED60","T1.75_LED.fp","unknown")
ElementSetAttr("LED60","device","LED")
ElementSetAttr("LED60","manufacturer","unknown")
ElementSetAttr("LED60","manufacturer_part_number","unknown")
ElementSetAttr("LED60","vendor","unknown")
ElementSetAttr("LED60","vendor_part_number","unknown")
ChangePinName("LED60", 2, "K")
ChangePinName("LED60", 1, "A")
ElementList(Need,"LED58","T1.75_LED.fp","unknown")
ElementSetAttr("LED58","device","LED")
ElementSetAttr("LED58","manufacturer","unknown")
ElementSetAttr("LED58","manufacturer_part_number","unknown")
ElementSetAttr("LED58","vendor","unknown")
ElementSetAttr("LED58","vendor_part_number","unknown")
ChangePinName("LED58", 2, "K")
ChangePinName("LED58", 1, "A")
ElementList(Need,"LED56","T1.75_LED.fp","unknown")
ElementSetAttr("LED56","device","LED")
ElementSetAttr("LED56","manufacturer","unknown")
ElementSetAttr("LED56","manufacturer_part_number","unknown")
ElementSetAttr("LED56","vendor","unknown")
ElementSetAttr("LED56","vendor_part_number","unknown")
ChangePinName("LED56", 2, "K")
ChangePinName("LED56", 1, "A")
ElementList(Need,"LED47","T1.75_LED.fp","unknown")
ElementSetAttr("LED47","device","LED")
ElementSetAttr("LED47","manufacturer","unknown")
ElementSetAttr("LED47","manufacturer_part_number","unknown")
ElementSetAttr("LED47","vendor","unknown")
ElementSetAttr("LED47","vendor_part_number","unknown")
ChangePinName("LED47", 2, "K")
ChangePinName("LED47", 1, "A")
ElementList(Need,"LED41","T1.75_LED.fp","unknown")
ElementSetAttr("LED41","device","LED")
ElementSetAttr("LED41","manufacturer","unknown")
ElementSetAttr("LED41","manufacturer_part_number","unknown")
ElementSetAttr("LED41","vendor","unknown")
ElementSetAttr("LED41","vendor_part_number","unknown")
ChangePinName("LED41", 2, "K")
ChangePinName("LED41", 1, "A")
ElementList(Need,"LED39","T1.75_LED.fp","unknown")
ElementSetAttr("LED39","device","LED")
ElementSetAttr("LED39","manufacturer","unknown")
ElementSetAttr("LED39","manufacturer_part_number","unknown")
ElementSetAttr("LED39","vendor","unknown")
ElementSetAttr("LED39","vendor_part_number","unknown")
ChangePinName("LED39", 2, "K")
ChangePinName("LED39", 1, "A")
ElementList(Need,"LED44","T1.75_LED.fp","unknown")
ElementSetAttr("LED44","device","LED")
ElementSetAttr("LED44","manufacturer","unknown")
ElementSetAttr("LED44","manufacturer_part_number","unknown")
ElementSetAttr("LED44","vendor","unknown")
ElementSetAttr("LED44","vendor_part_number","unknown")
ChangePinName("LED44", 2, "K")
ChangePinName("LED44", 1, "A")
ElementList(Need,"LED42","T1.75_LED.fp","unknown")
ElementSetAttr("LED42","device","LED")
ElementSetAttr("LED42","manufacturer","unknown")
ElementSetAttr("LED42","manufacturer_part_number","unknown")
ElementSetAttr("LED42","vendor","unknown")
ElementSetAttr("LED42","vendor_part_number","unknown")
ChangePinName("LED42", 2, "K")
ChangePinName("LED42", 1, "A")
ElementList(Need,"LED37","T1.75_LED.fp","unknown")
ElementSetAttr("LED37","device","LED")
ElementSetAttr("LED37","manufacturer","unknown")
ElementSetAttr("LED37","manufacturer_part_number","unknown")
ElementSetAttr("LED37","vendor","unknown")
ElementSetAttr("LED37","vendor_part_number","unknown")
ChangePinName("LED37", 2, "K")
ChangePinName("LED37", 1, "A")
ElementList(Need,"LED35","T1.75_LED.fp","unknown")
ElementSetAttr("LED35","device","LED")
ElementSetAttr("LED35","manufacturer","unknown")
ElementSetAttr("LED35","manufacturer_part_number","unknown")
ElementSetAttr("LED35","vendor","unknown")
ElementSetAttr("LED35","vendor_part_number","unknown")
ChangePinName("LED35", 2, "K")
ChangePinName("LED35", 1, "A")
ElementList(Need,"LED33","T1.75_LED.fp","unknown")
ElementSetAttr("LED33","device","LED")
ElementSetAttr("LED33","manufacturer","unknown")
ElementSetAttr("LED33","manufacturer_part_number","unknown")
ElementSetAttr("LED33","vendor","unknown")
ElementSetAttr("LED33","vendor_part_number","unknown")
ChangePinName("LED33", 2, "K")
ChangePinName("LED33", 1, "A")
ElementList(Need,"LED31","T1.75_LED.fp","unknown")
ElementSetAttr("LED31","device","LED")
ElementSetAttr("LED31","manufacturer","unknown")
ElementSetAttr("LED31","manufacturer_part_number","unknown")
ElementSetAttr("LED31","vendor","unknown")
ElementSetAttr("LED31","vendor_part_number","unknown")
ChangePinName("LED31", 2, "K")
ChangePinName("LED31", 1, "A")
ElementList(Need,"LED29","T1.75_LED.fp","unknown")
ElementSetAttr("LED29","device","LED")
ElementSetAttr("LED29","manufacturer","unknown")
ElementSetAttr("LED29","manufacturer_part_number","unknown")
ElementSetAttr("LED29","vendor","unknown")
ElementSetAttr("LED29","vendor_part_number","unknown")
ChangePinName("LED29", 2, "K")
ChangePinName("LED29", 1, "A")
ElementList(Need,"LED38","T1.75_LED.fp","unknown")
ElementSetAttr("LED38","device","LED")
ElementSetAttr("LED38","manufacturer","unknown")
ElementSetAttr("LED38","manufacturer_part_number","unknown")
ElementSetAttr("LED38","vendor","unknown")
ElementSetAttr("LED38","vendor_part_number","unknown")
ChangePinName("LED38", 2, "K")
ChangePinName("LED38", 1, "A")
ElementList(Need,"LED36","T1.75_LED.fp","unknown")
ElementSetAttr("LED36","device","LED")
ElementSetAttr("LED36","manufacturer","unknown")
ElementSetAttr("LED36","manufacturer_part_number","unknown")
ElementSetAttr("LED36","vendor","unknown")
ElementSetAttr("LED36","vendor_part_number","unknown")
ChangePinName("LED36", 2, "K")
ChangePinName("LED36", 1, "A")
ElementList(Need,"LED34","T1.75_LED.fp","unknown")
ElementSetAttr("LED34","device","LED")
ElementSetAttr("LED34","manufacturer","unknown")
ElementSetAttr("LED34","manufacturer_part_number","unknown")
ElementSetAttr("LED34","vendor","unknown")
ElementSetAttr("LED34","vendor_part_number","unknown")
ChangePinName("LED34", 2, "K")
ChangePinName("LED34", 1, "A")
ElementList(Need,"LED32","T1.75_LED.fp","unknown")
ElementSetAttr("LED32","device","LED")
ElementSetAttr("LED32","manufacturer","unknown")
ElementSetAttr("LED32","manufacturer_part_number","unknown")
ElementSetAttr("LED32","vendor","unknown")
ElementSetAttr("LED32","vendor_part_number","unknown")
ChangePinName("LED32", 2, "K")
ChangePinName("LED32", 1, "A")
ElementList(Need,"LED30","T1.75_LED.fp","unknown")
ElementSetAttr("LED30","device","LED")
ElementSetAttr("LED30","manufacturer","unknown")
ElementSetAttr("LED30","manufacturer_part_number","unknown")
ElementSetAttr("LED30","vendor","unknown")
ElementSetAttr("LED30","vendor_part_number","unknown")
ChangePinName("LED30", 2, "K")
ChangePinName("LED30", 1, "A")
ElementList(Done)
